// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/note/v1/note.proto

package notev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "note/api/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNotesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Tag             string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,3,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	OnlyArchived    bool                   `protobuf:"varint,4,opt,name=only_archived,json=onlyArchived,proto3" json:"only_archived,omitempty"`
	Lite            bool                   `protobuf:"varint,5,opt,name=lite,proto3" json:"lite,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListNotesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListNotesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListNotesRequest) GetOnlyArchived() bool {
	if x != nil {
		return x.OnlyArchived
	}
	return false
}

func (x *ListNotesRequest) GetLite() bool {
	if x != nil {
		return x.Lite
	}
	return false
}

type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*v1.Note             `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotesResponse) GetNotes() []*v1.Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *CreateNoteRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateNoteRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *UpdateNoteRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateNoteRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNoteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PinNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNoteRequest) Reset() {
	*x = PinNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNoteRequest) ProtoMessage() {}

func (x *PinNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNoteRequest.ProtoReflect.Descriptor instead.
func (*PinNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{7}
}

func (x *PinNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PinNoteRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ArchiveNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveNoteRequest) Reset() {
	*x = ArchiveNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveNoteRequest) ProtoMessage() {}

func (x *ArchiveNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveNoteRequest.ProtoReflect.Descriptor instead.
func (*ArchiveNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArchiveNoteRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type SetNoteStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNoteStatusRequest) Reset() {
	*x = SetNoteStatusRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNoteStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNoteStatusRequest) ProtoMessage() {}

func (x *SetNoteStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNoteStatusRequest.ProtoReflect.Descriptor instead.
func (*SetNoteStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{9}
}

func (x *SetNoteStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetNoteStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DuplicateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuplicateNoteRequest) Reset() {
	*x = DuplicateNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateNoteRequest) ProtoMessage() {}

func (x *DuplicateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateNoteRequest.ProtoReflect.Descriptor instead.
func (*DuplicateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{10}
}

func (x *DuplicateNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExportNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNoteRequest) Reset() {
	*x = ExportNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNoteRequest) ProtoMessage() {}

func (x *ExportNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNoteRequest.ProtoReflect.Descriptor instead.
func (*ExportNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{11}
}

func (x *ExportNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExportNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNoteResponse) Reset() {
	*x = ExportNoteResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNoteResponse) ProtoMessage() {}

func (x *ExportNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNoteResponse.ProtoReflect.Descriptor instead.
func (*ExportNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{12}
}

func (x *ExportNoteResponse) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *ExportNoteResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{13}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{14}
}

func (x *ListTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTagResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{17}
}

func (x *ListBlocksRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*v1.NoteBlock        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{18}
}

func (x *ListBlocksResponse) GetBlocks() []*v1.NoteBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ReplaceBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Blocks        []*v1.NoteBlock        `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceBlocksRequest) Reset() {
	*x = ReplaceBlocksRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceBlocksRequest) ProtoMessage() {}

func (x *ReplaceBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceBlocksRequest.ProtoReflect.Descriptor instead.
func (*ReplaceBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{19}
}

func (x *ReplaceBlocksRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *ReplaceBlocksRequest) GetBlocks() []*v1.NoteBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ReplaceBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *v1.Note               `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Blocks        []*v1.NoteBlock        `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceBlocksResponse) Reset() {
	*x = ReplaceBlocksResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceBlocksResponse) ProtoMessage() {}

func (x *ReplaceBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceBlocksResponse.ProtoReflect.Descriptor instead.
func (*ReplaceBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{20}
}

func (x *ReplaceBlocksResponse) GetNote() *v1.Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *ReplaceBlocksResponse) GetBlocks() []*v1.NoteBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{21}
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{22}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{23}
}

func (x *Template) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Template) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateFromTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFromTemplateRequest) Reset() {
	*x = CreateFromTemplateRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFromTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFromTemplateRequest) ProtoMessage() {}

func (x *CreateFromTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFromTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateFromTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{24}
}

func (x *CreateFromTemplateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateFromTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ImportNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNoteRequest) Reset() {
	*x = ImportNoteRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNoteRequest) ProtoMessage() {}

func (x *ImportNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNoteRequest.ProtoReflect.Descriptor instead.
func (*ImportNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{25}
}

func (x *ImportNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportNoteRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *ImportNoteRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RenderMarkdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderMarkdownRequest) Reset() {
	*x = RenderMarkdownRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderMarkdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderMarkdownRequest) ProtoMessage() {}

func (x *RenderMarkdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderMarkdownRequest.ProtoReflect.Descriptor instead.
func (*RenderMarkdownRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{26}
}

func (x *RenderMarkdownRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type RenderMarkdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderMarkdownResponse) Reset() {
	*x = RenderMarkdownResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderMarkdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderMarkdownResponse) ProtoMessage() {}

func (x *RenderMarkdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderMarkdownResponse.ProtoReflect.Descriptor instead.
func (*RenderMarkdownResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{27}
}

func (x *RenderMarkdownResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{28}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskItem            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{29}
}

func (x *ListTasksResponse) GetTasks() []*TaskItem {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	NoteTitle     string                 `protobuf:"bytes,2,opt,name=note_title,json=noteTitle,proto3" json:"note_title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Checked       bool                   `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	mi := &file_api_proto_note_v1_note_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_note_v1_note_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_api_proto_note_v1_note_proto_rawDescGZIP(), []int{30}
}

func (x *TaskItem) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *TaskItem) GetNoteTitle() string {
	if x != nil {
		return x.NoteTitle
	}
	return ""
}

func (x *TaskItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskItem) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

var File_api_proto_note_v1_note_proto protoreflect.FileDescriptor

const file_api_proto_note_v1_note_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/note/v1/note.proto\x12\fnote.note.v1\x1a api/proto/common/v1/common.proto\"\x9e\x01\n" +
	"\x10ListNotesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12)\n" +
	"\x10include_archived\x18\x03 \x01(\bR\x0fincludeArchived\x12#\n" +
	"\ronly_archived\x18\x04 \x01(\bR\fonlyArchived\x12\x12\n" +
	"\x04lite\x18\x05 \x01(\bR\x04lite\"?\n" +
	"\x11ListNotesResponse\x12*\n" +
	"\x05notes\x18\x01 \x03(\v2\x14.note.common.v1.NoteR\x05notes\" \n" +
	"\x0eGetNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"v\n" +
	"\x11CreateNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x86\x01\n" +
	"\x11UpdateNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x03 \x01(\tR\bmarkdown\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"#\n" +
	"\x11DeleteNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteNoteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\x0ePinNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\":\n" +
	"\x12ArchiveNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\">\n" +
	"\x14SetNoteStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"&\n" +
	"\x14DuplicateNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11ExportNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x12ExportNoteResponse\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\x11\n" +
	"\x0fListTagsRequest\"&\n" +
	"\x10ListTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"$\n" +
	"\x10DeleteTagRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"#\n" +
	"\x11DeleteTagResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\",\n" +
	"\x11ListBlocksRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"G\n" +
	"\x12ListBlocksResponse\x121\n" +
	"\x06blocks\x18\x01 \x03(\v2\x19.note.common.v1.NoteBlockR\x06blocks\"b\n" +
	"\x14ReplaceBlocksRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x121\n" +
	"\x06blocks\x18\x02 \x03(\v2\x19.note.common.v1.NoteBlockR\x06blocks\"t\n" +
	"\x15ReplaceBlocksResponse\x12(\n" +
	"\x04note\x18\x01 \x01(\v2\x14.note.common.v1.NoteR\x04note\x121\n" +
	"\x06blocks\x18\x02 \x03(\v2\x19.note.common.v1.NoteBlockR\x06blocks\"\x16\n" +
	"\x14ListTemplatesRequest\"M\n" +
	"\x15ListTemplatesResponse\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.note.note.v1.TemplateR\ttemplates\"T\n" +
	"\bTemplate\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"C\n" +
	"\x19CreateFromTemplateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"Y\n" +
	"\x11ImportNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"3\n" +
	"\x15RenderMarkdownRequest\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\",\n" +
	"\x16RenderMarkdownResponse\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\"\x12\n" +
	"\x10ListTasksRequest\"A\n" +
	"\x11ListTasksResponse\x12,\n" +
	"\x05tasks\x18\x01 \x03(\v2\x16.note.note.v1.TaskItemR\x05tasks\"v\n" +
	"\bTaskItem\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1d\n" +
	"\n" +
	"note_title\x18\x02 \x01(\tR\tnoteTitle\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\achecked\x18\x04 \x01(\bR\achecked2\xc5\v\n" +
	"\vNoteService\x12L\n" +
	"\tListNotes\x12\x1e.note.note.v1.ListNotesRequest\x1a\x1f.note.note.v1.ListNotesResponse\x12=\n" +
	"\aGetNote\x12\x1c.note.note.v1.GetNoteRequest\x1a\x14.note.common.v1.Note\x12C\n" +
	"\n" +
	"CreateNote\x12\x1f.note.note.v1.CreateNoteRequest\x1a\x14.note.common.v1.Note\x12C\n" +
	"\n" +
	"UpdateNote\x12\x1f.note.note.v1.UpdateNoteRequest\x1a\x14.note.common.v1.Note\x12O\n" +
	"\n" +
	"DeleteNote\x12\x1f.note.note.v1.DeleteNoteRequest\x1a .note.note.v1.DeleteNoteResponse\x12=\n" +
	"\aPinNote\x12\x1c.note.note.v1.PinNoteRequest\x1a\x14.note.common.v1.Note\x12E\n" +
	"\vArchiveNote\x12 .note.note.v1.ArchiveNoteRequest\x1a\x14.note.common.v1.Note\x12I\n" +
	"\rSetNoteStatus\x12\".note.note.v1.SetNoteStatusRequest\x1a\x14.note.common.v1.Note\x12I\n" +
	"\rDuplicateNote\x12\".note.note.v1.DuplicateNoteRequest\x1a\x14.note.common.v1.Note\x12O\n" +
	"\n" +
	"ExportNote\x12\x1f.note.note.v1.ExportNoteRequest\x1a .note.note.v1.ExportNoteResponse\x12I\n" +
	"\bListTags\x12\x1d.note.note.v1.ListTagsRequest\x1a\x1e.note.note.v1.ListTagsResponse\x12L\n" +
	"\tDeleteTag\x12\x1e.note.note.v1.DeleteTagRequest\x1a\x1f.note.note.v1.DeleteTagResponse\x12O\n" +
	"\n" +
	"ListBlocks\x12\x1f.note.note.v1.ListBlocksRequest\x1a .note.note.v1.ListBlocksResponse\x12X\n" +
	"\rReplaceBlocks\x12\".note.note.v1.ReplaceBlocksRequest\x1a#.note.note.v1.ReplaceBlocksResponse\x12X\n" +
	"\rListTemplates\x12\".note.note.v1.ListTemplatesRequest\x1a#.note.note.v1.ListTemplatesResponse\x12S\n" +
	"\x12CreateFromTemplate\x12'.note.note.v1.CreateFromTemplateRequest\x1a\x14.note.common.v1.Note\x12C\n" +
	"\n" +
	"ImportNote\x12\x1f.note.note.v1.ImportNoteRequest\x1a\x14.note.common.v1.Note\x12[\n" +
	"\x0eRenderMarkdown\x12#.note.note.v1.RenderMarkdownRequest\x1a$.note.note.v1.RenderMarkdownResponse\x12L\n" +
	"\tListTasks\x12\x1e.note.note.v1.ListTasksRequest\x1a\x1f.note.note.v1.ListTasksResponseB\x1fZ\x1dnote/api/proto/note/v1;notev1b\x06proto3"

var (
	file_api_proto_note_v1_note_proto_rawDescOnce sync.Once
	file_api_proto_note_v1_note_proto_rawDescData []byte
)

func file_api_proto_note_v1_note_proto_rawDescGZIP() []byte {
	file_api_proto_note_v1_note_proto_rawDescOnce.Do(func() {
		file_api_proto_note_v1_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_note_v1_note_proto_rawDesc), len(file_api_proto_note_v1_note_proto_rawDesc)))
	})
	return file_api_proto_note_v1_note_proto_rawDescData
}

var file_api_proto_note_v1_note_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_proto_note_v1_note_proto_goTypes = []any{
	(*ListNotesRequest)(nil),          // 0: note.note.v1.ListNotesRequest
	(*ListNotesResponse)(nil),         // 1: note.note.v1.ListNotesResponse
	(*GetNoteRequest)(nil),            // 2: note.note.v1.GetNoteRequest
	(*CreateNoteRequest)(nil),         // 3: note.note.v1.CreateNoteRequest
	(*UpdateNoteRequest)(nil),         // 4: note.note.v1.UpdateNoteRequest
	(*DeleteNoteRequest)(nil),         // 5: note.note.v1.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),        // 6: note.note.v1.DeleteNoteResponse
	(*PinNoteRequest)(nil),            // 7: note.note.v1.PinNoteRequest
	(*ArchiveNoteRequest)(nil),        // 8: note.note.v1.ArchiveNoteRequest
	(*SetNoteStatusRequest)(nil),      // 9: note.note.v1.SetNoteStatusRequest
	(*DuplicateNoteRequest)(nil),      // 10: note.note.v1.DuplicateNoteRequest
	(*ExportNoteRequest)(nil),         // 11: note.note.v1.ExportNoteRequest
	(*ExportNoteResponse)(nil),        // 12: note.note.v1.ExportNoteResponse
	(*ListTagsRequest)(nil),           // 13: note.note.v1.ListTagsRequest
	(*ListTagsResponse)(nil),          // 14: note.note.v1.ListTagsResponse
	(*DeleteTagRequest)(nil),          // 15: note.note.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil),         // 16: note.note.v1.DeleteTagResponse
	(*ListBlocksRequest)(nil),         // 17: note.note.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),        // 18: note.note.v1.ListBlocksResponse
	(*ReplaceBlocksRequest)(nil),      // 19: note.note.v1.ReplaceBlocksRequest
	(*ReplaceBlocksResponse)(nil),     // 20: note.note.v1.ReplaceBlocksResponse
	(*ListTemplatesRequest)(nil),      // 21: note.note.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),     // 22: note.note.v1.ListTemplatesResponse
	(*Template)(nil),                  // 23: note.note.v1.Template
	(*CreateFromTemplateRequest)(nil), // 24: note.note.v1.CreateFromTemplateRequest
	(*ImportNoteRequest)(nil),         // 25: note.note.v1.ImportNoteRequest
	(*RenderMarkdownRequest)(nil),     // 26: note.note.v1.RenderMarkdownRequest
	(*RenderMarkdownResponse)(nil),    // 27: note.note.v1.RenderMarkdownResponse
	(*ListTasksRequest)(nil),          // 28: note.note.v1.ListTasksRequest
	(*ListTasksResponse)(nil),         // 29: note.note.v1.ListTasksResponse
	(*TaskItem)(nil),                  // 30: note.note.v1.TaskItem
	(*v1.Note)(nil),                   // 31: note.common.v1.Note
	(*v1.NoteBlock)(nil),              // 32: note.common.v1.NoteBlock
}
var file_api_proto_note_v1_note_proto_depIdxs = []int32{
	31, // 0: note.note.v1.ListNotesResponse.notes:type_name -> note.common.v1.Note
	32, // 1: note.note.v1.ListBlocksResponse.blocks:type_name -> note.common.v1.NoteBlock
	32, // 2: note.note.v1.ReplaceBlocksRequest.blocks:type_name -> note.common.v1.NoteBlock
	31, // 3: note.note.v1.ReplaceBlocksResponse.note:type_name -> note.common.v1.Note
	32, // 4: note.note.v1.ReplaceBlocksResponse.blocks:type_name -> note.common.v1.NoteBlock
	23, // 5: note.note.v1.ListTemplatesResponse.templates:type_name -> note.note.v1.Template
	30, // 6: note.note.v1.ListTasksResponse.tasks:type_name -> note.note.v1.TaskItem
	0,  // 7: note.note.v1.NoteService.ListNotes:input_type -> note.note.v1.ListNotesRequest
	2,  // 8: note.note.v1.NoteService.GetNote:input_type -> note.note.v1.GetNoteRequest
	3,  // 9: note.note.v1.NoteService.CreateNote:input_type -> note.note.v1.CreateNoteRequest
	4,  // 10: note.note.v1.NoteService.UpdateNote:input_type -> note.note.v1.UpdateNoteRequest
	5,  // 11: note.note.v1.NoteService.DeleteNote:input_type -> note.note.v1.DeleteNoteRequest
	7,  // 12: note.note.v1.NoteService.PinNote:input_type -> note.note.v1.PinNoteRequest
	8,  // 13: note.note.v1.NoteService.ArchiveNote:input_type -> note.note.v1.ArchiveNoteRequest
	9,  // 14: note.note.v1.NoteService.SetNoteStatus:input_type -> note.note.v1.SetNoteStatusRequest
	10, // 15: note.note.v1.NoteService.DuplicateNote:input_type -> note.note.v1.DuplicateNoteRequest
	11, // 16: note.note.v1.NoteService.ExportNote:input_type -> note.note.v1.ExportNoteRequest
	13, // 17: note.note.v1.NoteService.ListTags:input_type -> note.note.v1.ListTagsRequest
	15, // 18: note.note.v1.NoteService.DeleteTag:input_type -> note.note.v1.DeleteTagRequest
	17, // 19: note.note.v1.NoteService.ListBlocks:input_type -> note.note.v1.ListBlocksRequest
	19, // 20: note.note.v1.NoteService.ReplaceBlocks:input_type -> note.note.v1.ReplaceBlocksRequest
	21, // 21: note.note.v1.NoteService.ListTemplates:input_type -> note.note.v1.ListTemplatesRequest
	24, // 22: note.note.v1.NoteService.CreateFromTemplate:input_type -> note.note.v1.CreateFromTemplateRequest
	25, // 23: note.note.v1.NoteService.ImportNote:input_type -> note.note.v1.ImportNoteRequest
	26, // 24: note.note.v1.NoteService.RenderMarkdown:input_type -> note.note.v1.RenderMarkdownRequest
	28, // 25: note.note.v1.NoteService.ListTasks:input_type -> note.note.v1.ListTasksRequest
	1,  // 26: note.note.v1.NoteService.ListNotes:output_type -> note.note.v1.ListNotesResponse
	31, // 27: note.note.v1.NoteService.GetNote:output_type -> note.common.v1.Note
	31, // 28: note.note.v1.NoteService.CreateNote:output_type -> note.common.v1.Note
	31, // 29: note.note.v1.NoteService.UpdateNote:output_type -> note.common.v1.Note
	6,  // 30: note.note.v1.NoteService.DeleteNote:output_type -> note.note.v1.DeleteNoteResponse
	31, // 31: note.note.v1.NoteService.PinNote:output_type -> note.common.v1.Note
	31, // 32: note.note.v1.NoteService.ArchiveNote:output_type -> note.common.v1.Note
	31, // 33: note.note.v1.NoteService.SetNoteStatus:output_type -> note.common.v1.Note
	31, // 34: note.note.v1.NoteService.DuplicateNote:output_type -> note.common.v1.Note
	12, // 35: note.note.v1.NoteService.ExportNote:output_type -> note.note.v1.ExportNoteResponse
	14, // 36: note.note.v1.NoteService.ListTags:output_type -> note.note.v1.ListTagsResponse
	16, // 37: note.note.v1.NoteService.DeleteTag:output_type -> note.note.v1.DeleteTagResponse
	18, // 38: note.note.v1.NoteService.ListBlocks:output_type -> note.note.v1.ListBlocksResponse
	20, // 39: note.note.v1.NoteService.ReplaceBlocks:output_type -> note.note.v1.ReplaceBlocksResponse
	22, // 40: note.note.v1.NoteService.ListTemplates:output_type -> note.note.v1.ListTemplatesResponse
	31, // 41: note.note.v1.NoteService.CreateFromTemplate:output_type -> note.common.v1.Note
	31, // 42: note.note.v1.NoteService.ImportNote:output_type -> note.common.v1.Note
	27, // 43: note.note.v1.NoteService.RenderMarkdown:output_type -> note.note.v1.RenderMarkdownResponse
	29, // 44: note.note.v1.NoteService.ListTasks:output_type -> note.note.v1.ListTasksResponse
	26, // [26:45] is the sub-list for method output_type
	7,  // [7:26] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_note_v1_note_proto_init() }
func file_api_proto_note_v1_note_proto_init() {
	if File_api_proto_note_v1_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_note_v1_note_proto_rawDesc), len(file_api_proto_note_v1_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_note_v1_note_proto_goTypes,
		DependencyIndexes: file_api_proto_note_v1_note_proto_depIdxs,
		MessageInfos:      file_api_proto_note_v1_note_proto_msgTypes,
	}.Build()
	File_api_proto_note_v1_note_proto = out.File
	file_api_proto_note_v1_note_proto_goTypes = nil
	file_api_proto_note_v1_note_proto_depIdxs = nil
}
