// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.1
// source: api/proto/intelligence/v1/intelligence.proto

package intelligencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "note/api/proto/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntelligenceService_GetNoteInsights_FullMethodName             = "/note.intelligence.v1.IntelligenceService/GetNoteInsights"
	IntelligenceService_SuggestTags_FullMethodName                 = "/note.intelligence.v1.IntelligenceService/SuggestTags"
	IntelligenceService_GetNoteRecommendations_FullMethodName      = "/note.intelligence.v1.IntelligenceService/GetNoteRecommendations"
	IntelligenceService_GetNoteLinks_FullMethodName                = "/note.intelligence.v1.IntelligenceService/GetNoteLinks"
	IntelligenceService_ListReviewQuestions_FullMethodName         = "/note.intelligence.v1.IntelligenceService/ListReviewQuestions"
	IntelligenceService_CreateReviewQuestion_FullMethodName        = "/note.intelligence.v1.IntelligenceService/CreateReviewQuestion"
	IntelligenceService_GenerateReviewQuestions_FullMethodName     = "/note.intelligence.v1.IntelligenceService/GenerateReviewQuestions"
	IntelligenceService_UpdateReviewQuestion_FullMethodName        = "/note.intelligence.v1.IntelligenceService/UpdateReviewQuestion"
	IntelligenceService_DeleteReviewQuestion_FullMethodName        = "/note.intelligence.v1.IntelligenceService/DeleteReviewQuestion"
	IntelligenceService_GetDailyReview_FullMethodName              = "/note.intelligence.v1.IntelligenceService/GetDailyReview"
	IntelligenceService_CreateAIRecommendation_FullMethodName      = "/note.intelligence.v1.IntelligenceService/CreateAIRecommendation"
	IntelligenceService_ListRecommendationSessions_FullMethodName  = "/note.intelligence.v1.IntelligenceService/ListRecommendationSessions"
	IntelligenceService_DeleteRecommendationSession_FullMethodName = "/note.intelligence.v1.IntelligenceService/DeleteRecommendationSession"
	IntelligenceService_CreateResearchSession_FullMethodName       = "/note.intelligence.v1.IntelligenceService/CreateResearchSession"
	IntelligenceService_ListResearchSessions_FullMethodName        = "/note.intelligence.v1.IntelligenceService/ListResearchSessions"
	IntelligenceService_DeleteResearchSession_FullMethodName       = "/note.intelligence.v1.IntelligenceService/DeleteResearchSession"
	IntelligenceService_CreateWeeklyReport_FullMethodName          = "/note.intelligence.v1.IntelligenceService/CreateWeeklyReport"
	IntelligenceService_OptimizeNote_FullMethodName                = "/note.intelligence.v1.IntelligenceService/OptimizeNote"
)

// IntelligenceServiceClient is the client API for IntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IntelligenceService AI 智能洞察服务。
type IntelligenceServiceClient interface {
	GetNoteInsights(ctx context.Context, in *GetNoteInsightsRequest, opts ...grpc.CallOption) (*NoteInsightsResponse, error)
	SuggestTags(ctx context.Context, in *SuggestTagsRequest, opts ...grpc.CallOption) (*SuggestTagsResponse, error)
	GetNoteRecommendations(ctx context.Context, in *GetNoteRecommendationsRequest, opts ...grpc.CallOption) (*NoteRecommendationsResponse, error)
	GetNoteLinks(ctx context.Context, in *GetNoteLinksRequest, opts ...grpc.CallOption) (*NoteLinksResponse, error)
	// Review Questions
	ListReviewQuestions(ctx context.Context, in *ListReviewQuestionsRequest, opts ...grpc.CallOption) (*ListReviewQuestionsResponse, error)
	CreateReviewQuestion(ctx context.Context, in *CreateReviewQuestionRequest, opts ...grpc.CallOption) (*v1.ReviewQuestion, error)
	GenerateReviewQuestions(ctx context.Context, in *GenerateReviewQuestionsRequest, opts ...grpc.CallOption) (*GenerateReviewQuestionsResponse, error)
	UpdateReviewQuestion(ctx context.Context, in *UpdateReviewQuestionRequest, opts ...grpc.CallOption) (*v1.ReviewQuestion, error)
	DeleteReviewQuestion(ctx context.Context, in *DeleteReviewQuestionRequest, opts ...grpc.CallOption) (*DeleteReviewQuestionResponse, error)
	GetDailyReview(ctx context.Context, in *GetDailyReviewRequest, opts ...grpc.CallOption) (*DailyReviewResponse, error)
	// Recommendations
	CreateAIRecommendation(ctx context.Context, in *CreateAIRecommendationRequest, opts ...grpc.CallOption) (*AIRecommendationResponse, error)
	ListRecommendationSessions(ctx context.Context, in *ListRecommendationSessionsRequest, opts ...grpc.CallOption) (*ListRecommendationSessionsResponse, error)
	DeleteRecommendationSession(ctx context.Context, in *DeleteRecommendationSessionRequest, opts ...grpc.CallOption) (*DeleteRecommendationSessionResponse, error)
	// Research Sessions
	CreateResearchSession(ctx context.Context, in *CreateResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionResponse, error)
	ListResearchSessions(ctx context.Context, in *ListResearchSessionsRequest, opts ...grpc.CallOption) (*ListResearchSessionsResponse, error)
	DeleteResearchSession(ctx context.Context, in *DeleteResearchSessionRequest, opts ...grpc.CallOption) (*DeleteResearchSessionResponse, error)
	// Writing
	CreateWeeklyReport(ctx context.Context, in *CreateWeeklyReportRequest, opts ...grpc.CallOption) (*WeeklyReportResponse, error)
	// Optimize
	OptimizeNote(ctx context.Context, in *OptimizeNoteRequest, opts ...grpc.CallOption) (*OptimizeNoteResponse, error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) GetNoteInsights(ctx context.Context, in *GetNoteInsightsRequest, opts ...grpc.CallOption) (*NoteInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteInsightsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GetNoteInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) SuggestTags(ctx context.Context, in *SuggestTagsRequest, opts ...grpc.CallOption) (*SuggestTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestTagsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_SuggestTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) GetNoteRecommendations(ctx context.Context, in *GetNoteRecommendationsRequest, opts ...grpc.CallOption) (*NoteRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteRecommendationsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GetNoteRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) GetNoteLinks(ctx context.Context, in *GetNoteLinksRequest, opts ...grpc.CallOption) (*NoteLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteLinksResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GetNoteLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) ListReviewQuestions(ctx context.Context, in *ListReviewQuestionsRequest, opts ...grpc.CallOption) (*ListReviewQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewQuestionsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_ListReviewQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) CreateReviewQuestion(ctx context.Context, in *CreateReviewQuestionRequest, opts ...grpc.CallOption) (*v1.ReviewQuestion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ReviewQuestion)
	err := c.cc.Invoke(ctx, IntelligenceService_CreateReviewQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) GenerateReviewQuestions(ctx context.Context, in *GenerateReviewQuestionsRequest, opts ...grpc.CallOption) (*GenerateReviewQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateReviewQuestionsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GenerateReviewQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) UpdateReviewQuestion(ctx context.Context, in *UpdateReviewQuestionRequest, opts ...grpc.CallOption) (*v1.ReviewQuestion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ReviewQuestion)
	err := c.cc.Invoke(ctx, IntelligenceService_UpdateReviewQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) DeleteReviewQuestion(ctx context.Context, in *DeleteReviewQuestionRequest, opts ...grpc.CallOption) (*DeleteReviewQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReviewQuestionResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_DeleteReviewQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) GetDailyReview(ctx context.Context, in *GetDailyReviewRequest, opts ...grpc.CallOption) (*DailyReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyReviewResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GetDailyReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) CreateAIRecommendation(ctx context.Context, in *CreateAIRecommendationRequest, opts ...grpc.CallOption) (*AIRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIRecommendationResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_CreateAIRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) ListRecommendationSessions(ctx context.Context, in *ListRecommendationSessionsRequest, opts ...grpc.CallOption) (*ListRecommendationSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationSessionsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_ListRecommendationSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) DeleteRecommendationSession(ctx context.Context, in *DeleteRecommendationSessionRequest, opts ...grpc.CallOption) (*DeleteRecommendationSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecommendationSessionResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_DeleteRecommendationSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) CreateResearchSession(ctx context.Context, in *CreateResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResearchSessionResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_CreateResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) ListResearchSessions(ctx context.Context, in *ListResearchSessionsRequest, opts ...grpc.CallOption) (*ListResearchSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResearchSessionsResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_ListResearchSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) DeleteResearchSession(ctx context.Context, in *DeleteResearchSessionRequest, opts ...grpc.CallOption) (*DeleteResearchSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResearchSessionResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_DeleteResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) CreateWeeklyReport(ctx context.Context, in *CreateWeeklyReportRequest, opts ...grpc.CallOption) (*WeeklyReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeeklyReportResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_CreateWeeklyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) OptimizeNote(ctx context.Context, in *OptimizeNoteRequest, opts ...grpc.CallOption) (*OptimizeNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeNoteResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_OptimizeNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelligenceServiceServer is the server API for IntelligenceService service.
// All implementations must embed UnimplementedIntelligenceServiceServer
// for forward compatibility.
//
// IntelligenceService AI 智能洞察服务。
type IntelligenceServiceServer interface {
	GetNoteInsights(context.Context, *GetNoteInsightsRequest) (*NoteInsightsResponse, error)
	SuggestTags(context.Context, *SuggestTagsRequest) (*SuggestTagsResponse, error)
	GetNoteRecommendations(context.Context, *GetNoteRecommendationsRequest) (*NoteRecommendationsResponse, error)
	GetNoteLinks(context.Context, *GetNoteLinksRequest) (*NoteLinksResponse, error)
	// Review Questions
	ListReviewQuestions(context.Context, *ListReviewQuestionsRequest) (*ListReviewQuestionsResponse, error)
	CreateReviewQuestion(context.Context, *CreateReviewQuestionRequest) (*v1.ReviewQuestion, error)
	GenerateReviewQuestions(context.Context, *GenerateReviewQuestionsRequest) (*GenerateReviewQuestionsResponse, error)
	UpdateReviewQuestion(context.Context, *UpdateReviewQuestionRequest) (*v1.ReviewQuestion, error)
	DeleteReviewQuestion(context.Context, *DeleteReviewQuestionRequest) (*DeleteReviewQuestionResponse, error)
	GetDailyReview(context.Context, *GetDailyReviewRequest) (*DailyReviewResponse, error)
	// Recommendations
	CreateAIRecommendation(context.Context, *CreateAIRecommendationRequest) (*AIRecommendationResponse, error)
	ListRecommendationSessions(context.Context, *ListRecommendationSessionsRequest) (*ListRecommendationSessionsResponse, error)
	DeleteRecommendationSession(context.Context, *DeleteRecommendationSessionRequest) (*DeleteRecommendationSessionResponse, error)
	// Research Sessions
	CreateResearchSession(context.Context, *CreateResearchSessionRequest) (*ResearchSessionResponse, error)
	ListResearchSessions(context.Context, *ListResearchSessionsRequest) (*ListResearchSessionsResponse, error)
	DeleteResearchSession(context.Context, *DeleteResearchSessionRequest) (*DeleteResearchSessionResponse, error)
	// Writing
	CreateWeeklyReport(context.Context, *CreateWeeklyReportRequest) (*WeeklyReportResponse, error)
	// Optimize
	OptimizeNote(context.Context, *OptimizeNoteRequest) (*OptimizeNoteResponse, error)
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelligenceServiceServer struct{}

func (UnimplementedIntelligenceServiceServer) GetNoteInsights(context.Context, *GetNoteInsightsRequest) (*NoteInsightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteInsights not implemented")
}
func (UnimplementedIntelligenceServiceServer) SuggestTags(context.Context, *SuggestTagsRequest) (*SuggestTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestTags not implemented")
}
func (UnimplementedIntelligenceServiceServer) GetNoteRecommendations(context.Context, *GetNoteRecommendationsRequest) (*NoteRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteRecommendations not implemented")
}
func (UnimplementedIntelligenceServiceServer) GetNoteLinks(context.Context, *GetNoteLinksRequest) (*NoteLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteLinks not implemented")
}
func (UnimplementedIntelligenceServiceServer) ListReviewQuestions(context.Context, *ListReviewQuestionsRequest) (*ListReviewQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReviewQuestions not implemented")
}
func (UnimplementedIntelligenceServiceServer) CreateReviewQuestion(context.Context, *CreateReviewQuestionRequest) (*v1.ReviewQuestion, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReviewQuestion not implemented")
}
func (UnimplementedIntelligenceServiceServer) GenerateReviewQuestions(context.Context, *GenerateReviewQuestionsRequest) (*GenerateReviewQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReviewQuestions not implemented")
}
func (UnimplementedIntelligenceServiceServer) UpdateReviewQuestion(context.Context, *UpdateReviewQuestionRequest) (*v1.ReviewQuestion, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReviewQuestion not implemented")
}
func (UnimplementedIntelligenceServiceServer) DeleteReviewQuestion(context.Context, *DeleteReviewQuestionRequest) (*DeleteReviewQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReviewQuestion not implemented")
}
func (UnimplementedIntelligenceServiceServer) GetDailyReview(context.Context, *GetDailyReviewRequest) (*DailyReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyReview not implemented")
}
func (UnimplementedIntelligenceServiceServer) CreateAIRecommendation(context.Context, *CreateAIRecommendationRequest) (*AIRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAIRecommendation not implemented")
}
func (UnimplementedIntelligenceServiceServer) ListRecommendationSessions(context.Context, *ListRecommendationSessionsRequest) (*ListRecommendationSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecommendationSessions not implemented")
}
func (UnimplementedIntelligenceServiceServer) DeleteRecommendationSession(context.Context, *DeleteRecommendationSessionRequest) (*DeleteRecommendationSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecommendationSession not implemented")
}
func (UnimplementedIntelligenceServiceServer) CreateResearchSession(context.Context, *CreateResearchSessionRequest) (*ResearchSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResearchSession not implemented")
}
func (UnimplementedIntelligenceServiceServer) ListResearchSessions(context.Context, *ListResearchSessionsRequest) (*ListResearchSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResearchSessions not implemented")
}
func (UnimplementedIntelligenceServiceServer) DeleteResearchSession(context.Context, *DeleteResearchSessionRequest) (*DeleteResearchSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResearchSession not implemented")
}
func (UnimplementedIntelligenceServiceServer) CreateWeeklyReport(context.Context, *CreateWeeklyReportRequest) (*WeeklyReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWeeklyReport not implemented")
}
func (UnimplementedIntelligenceServiceServer) OptimizeNote(context.Context, *OptimizeNoteRequest) (*OptimizeNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OptimizeNote not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}
func (UnimplementedIntelligenceServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServiceServer will
// result in compilation errors.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	// If the following call panics, it indicates UnimplementedIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_GetNoteInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetNoteInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetNoteInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetNoteInsights(ctx, req.(*GetNoteInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_SuggestTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).SuggestTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_SuggestTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).SuggestTags(ctx, req.(*SuggestTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_GetNoteRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetNoteRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetNoteRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetNoteRecommendations(ctx, req.(*GetNoteRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_GetNoteLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetNoteLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetNoteLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetNoteLinks(ctx, req.(*GetNoteLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_ListReviewQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).ListReviewQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_ListReviewQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).ListReviewQuestions(ctx, req.(*ListReviewQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_CreateReviewQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).CreateReviewQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_CreateReviewQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).CreateReviewQuestion(ctx, req.(*CreateReviewQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_GenerateReviewQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReviewQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GenerateReviewQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GenerateReviewQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GenerateReviewQuestions(ctx, req.(*GenerateReviewQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_UpdateReviewQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReviewQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).UpdateReviewQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_UpdateReviewQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).UpdateReviewQuestion(ctx, req.(*UpdateReviewQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_DeleteReviewQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).DeleteReviewQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_DeleteReviewQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).DeleteReviewQuestion(ctx, req.(*DeleteReviewQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_GetDailyReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetDailyReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetDailyReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetDailyReview(ctx, req.(*GetDailyReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_CreateAIRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAIRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).CreateAIRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_CreateAIRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).CreateAIRecommendation(ctx, req.(*CreateAIRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_ListRecommendationSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).ListRecommendationSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_ListRecommendationSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).ListRecommendationSessions(ctx, req.(*ListRecommendationSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_DeleteRecommendationSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecommendationSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).DeleteRecommendationSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_DeleteRecommendationSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).DeleteRecommendationSession(ctx, req.(*DeleteRecommendationSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_CreateResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).CreateResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_CreateResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).CreateResearchSession(ctx, req.(*CreateResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_ListResearchSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResearchSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).ListResearchSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_ListResearchSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).ListResearchSessions(ctx, req.(*ListResearchSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_DeleteResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).DeleteResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_DeleteResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).DeleteResearchSession(ctx, req.(*DeleteResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_CreateWeeklyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeeklyReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).CreateWeeklyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_CreateWeeklyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).CreateWeeklyReport(ctx, req.(*CreateWeeklyReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_OptimizeNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).OptimizeNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_OptimizeNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).OptimizeNote(ctx, req.(*OptimizeNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "note.intelligence.v1.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNoteInsights",
			Handler:    _IntelligenceService_GetNoteInsights_Handler,
		},
		{
			MethodName: "SuggestTags",
			Handler:    _IntelligenceService_SuggestTags_Handler,
		},
		{
			MethodName: "GetNoteRecommendations",
			Handler:    _IntelligenceService_GetNoteRecommendations_Handler,
		},
		{
			MethodName: "GetNoteLinks",
			Handler:    _IntelligenceService_GetNoteLinks_Handler,
		},
		{
			MethodName: "ListReviewQuestions",
			Handler:    _IntelligenceService_ListReviewQuestions_Handler,
		},
		{
			MethodName: "CreateReviewQuestion",
			Handler:    _IntelligenceService_CreateReviewQuestion_Handler,
		},
		{
			MethodName: "GenerateReviewQuestions",
			Handler:    _IntelligenceService_GenerateReviewQuestions_Handler,
		},
		{
			MethodName: "UpdateReviewQuestion",
			Handler:    _IntelligenceService_UpdateReviewQuestion_Handler,
		},
		{
			MethodName: "DeleteReviewQuestion",
			Handler:    _IntelligenceService_DeleteReviewQuestion_Handler,
		},
		{
			MethodName: "GetDailyReview",
			Handler:    _IntelligenceService_GetDailyReview_Handler,
		},
		{
			MethodName: "CreateAIRecommendation",
			Handler:    _IntelligenceService_CreateAIRecommendation_Handler,
		},
		{
			MethodName: "ListRecommendationSessions",
			Handler:    _IntelligenceService_ListRecommendationSessions_Handler,
		},
		{
			MethodName: "DeleteRecommendationSession",
			Handler:    _IntelligenceService_DeleteRecommendationSession_Handler,
		},
		{
			MethodName: "CreateResearchSession",
			Handler:    _IntelligenceService_CreateResearchSession_Handler,
		},
		{
			MethodName: "ListResearchSessions",
			Handler:    _IntelligenceService_ListResearchSessions_Handler,
		},
		{
			MethodName: "DeleteResearchSession",
			Handler:    _IntelligenceService_DeleteResearchSession_Handler,
		},
		{
			MethodName: "CreateWeeklyReport",
			Handler:    _IntelligenceService_CreateWeeklyReport_Handler,
		},
		{
			MethodName: "OptimizeNote",
			Handler:    _IntelligenceService_OptimizeNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/intelligence/v1/intelligence.proto",
}
