// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/intelligence/v1/intelligence.proto

package intelligencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "note/api/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNoteInsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Cached        bool                   `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteInsightsRequest) Reset() {
	*x = GetNoteInsightsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteInsightsRequest) ProtoMessage() {}

func (x *GetNoteInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteInsightsRequest.ProtoReflect.Descriptor instead.
func (*GetNoteInsightsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *GetNoteInsightsRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetNoteInsightsRequest) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type NoteInsightsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Outline         []string               `protobuf:"bytes,2,rep,name=outline,proto3" json:"outline,omitempty"`
	Keywords        []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	SuggestedTags   []string               `protobuf:"bytes,4,rep,name=suggested_tags,json=suggestedTags,proto3" json:"suggested_tags,omitempty"`
	QualityScore    int32                  `protobuf:"varint,5,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	QualityIssues   []*QualityIssue        `protobuf:"bytes,6,rep,name=quality_issues,json=qualityIssues,proto3" json:"quality_issues,omitempty"`
	Flashcards      []*v1.ReviewQuestion   `protobuf:"bytes,7,rep,name=flashcards,proto3" json:"flashcards,omitempty"`
	Recommendations []*v1.NoteReference    `protobuf:"bytes,8,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Links           *NoteLinksResponse     `protobuf:"bytes,9,opt,name=links,proto3" json:"links,omitempty"`
	UsedAi          bool                   `protobuf:"varint,10,opt,name=used_ai,json=usedAi,proto3" json:"used_ai,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NoteInsightsResponse) Reset() {
	*x = NoteInsightsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteInsightsResponse) ProtoMessage() {}

func (x *NoteInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteInsightsResponse.ProtoReflect.Descriptor instead.
func (*NoteInsightsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *NoteInsightsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *NoteInsightsResponse) GetOutline() []string {
	if x != nil {
		return x.Outline
	}
	return nil
}

func (x *NoteInsightsResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *NoteInsightsResponse) GetSuggestedTags() []string {
	if x != nil {
		return x.SuggestedTags
	}
	return nil
}

func (x *NoteInsightsResponse) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *NoteInsightsResponse) GetQualityIssues() []*QualityIssue {
	if x != nil {
		return x.QualityIssues
	}
	return nil
}

func (x *NoteInsightsResponse) GetFlashcards() []*v1.ReviewQuestion {
	if x != nil {
		return x.Flashcards
	}
	return nil
}

func (x *NoteInsightsResponse) GetRecommendations() []*v1.NoteReference {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *NoteInsightsResponse) GetLinks() *NoteLinksResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *NoteInsightsResponse) GetUsedAi() bool {
	if x != nil {
		return x.UsedAi
	}
	return false
}

type QualityIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Suggestion    string                 `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityIssue) Reset() {
	*x = QualityIssue{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityIssue) ProtoMessage() {}

func (x *QualityIssue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityIssue.ProtoReflect.Descriptor instead.
func (*QualityIssue) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *QualityIssue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QualityIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *QualityIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QualityIssue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type SuggestTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsRequest) Reset() {
	*x = SuggestTagsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsRequest) ProtoMessage() {}

func (x *SuggestTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsRequest.ProtoReflect.Descriptor instead.
func (*SuggestTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestTagsRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type SuggestTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	UsedAi        bool                   `protobuf:"varint,2,opt,name=used_ai,json=usedAi,proto3" json:"used_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsResponse) Reset() {
	*x = SuggestTagsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsResponse) ProtoMessage() {}

func (x *SuggestTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsResponse.ProtoReflect.Descriptor instead.
func (*SuggestTagsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SuggestTagsResponse) GetUsedAi() bool {
	if x != nil {
		return x.UsedAi
	}
	return false
}

type GetNoteRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRecommendationsRequest) Reset() {
	*x = GetNoteRecommendationsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRecommendationsRequest) ProtoMessage() {}

func (x *GetNoteRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *GetNoteRecommendationsRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type NoteRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*v1.NoteReference    `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteRecommendationsResponse) Reset() {
	*x = NoteRecommendationsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteRecommendationsResponse) ProtoMessage() {}

func (x *NoteRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*NoteRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *NoteRecommendationsResponse) GetNotes() []*v1.NoteReference {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetNoteLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteLinksRequest) Reset() {
	*x = GetNoteLinksRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteLinksRequest) ProtoMessage() {}

func (x *GetNoteLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteLinksRequest.ProtoReflect.Descriptor instead.
func (*GetNoteLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *GetNoteLinksRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type NoteLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incoming      []*v1.NoteReference    `protobuf:"bytes,1,rep,name=incoming,proto3" json:"incoming,omitempty"`
	Outgoing      []*v1.NoteReference    `protobuf:"bytes,2,rep,name=outgoing,proto3" json:"outgoing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteLinksResponse) Reset() {
	*x = NoteLinksResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteLinksResponse) ProtoMessage() {}

func (x *NoteLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteLinksResponse.ProtoReflect.Descriptor instead.
func (*NoteLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{8}
}

func (x *NoteLinksResponse) GetIncoming() []*v1.NoteReference {
	if x != nil {
		return x.Incoming
	}
	return nil
}

func (x *NoteLinksResponse) GetOutgoing() []*v1.NoteReference {
	if x != nil {
		return x.Outgoing
	}
	return nil
}

type ListReviewQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewQuestionsRequest) Reset() {
	*x = ListReviewQuestionsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewQuestionsRequest) ProtoMessage() {}

func (x *ListReviewQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{9}
}

func (x *ListReviewQuestionsRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type ListReviewQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*v1.ReviewQuestion   `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewQuestionsResponse) Reset() {
	*x = ListReviewQuestionsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewQuestionsResponse) ProtoMessage() {}

func (x *ListReviewQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{10}
}

func (x *ListReviewQuestionsResponse) GetQuestions() []*v1.ReviewQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CreateReviewQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewQuestionRequest) Reset() {
	*x = CreateReviewQuestionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewQuestionRequest) ProtoMessage() {}

func (x *CreateReviewQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewQuestionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{11}
}

func (x *CreateReviewQuestionRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *CreateReviewQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreateReviewQuestionRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *CreateReviewQuestionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GenerateReviewQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReviewQuestionsRequest) Reset() {
	*x = GenerateReviewQuestionsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReviewQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReviewQuestionsRequest) ProtoMessage() {}

func (x *GenerateReviewQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReviewQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateReviewQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateReviewQuestionsRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GenerateReviewQuestionsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenerateReviewQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       []*v1.ReviewQuestion   `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReviewQuestionsResponse) Reset() {
	*x = GenerateReviewQuestionsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReviewQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReviewQuestionsResponse) ProtoMessage() {}

func (x *GenerateReviewQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReviewQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateReviewQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateReviewQuestionsResponse) GetCreated() []*v1.ReviewQuestion {
	if x != nil {
		return x.Created
	}
	return nil
}

type UpdateReviewQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewQuestionRequest) Reset() {
	*x = UpdateReviewQuestionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewQuestionRequest) ProtoMessage() {}

func (x *UpdateReviewQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewQuestionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateReviewQuestionRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *UpdateReviewQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UpdateReviewQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UpdateReviewQuestionRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type DeleteReviewQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewQuestionRequest) Reset() {
	*x = DeleteReviewQuestionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewQuestionRequest) ProtoMessage() {}

func (x *DeleteReviewQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewQuestionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteReviewQuestionRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *DeleteReviewQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type DeleteReviewQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewQuestionResponse) Reset() {
	*x = DeleteReviewQuestionResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewQuestionResponse) ProtoMessage() {}

func (x *DeleteReviewQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewQuestionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteReviewQuestionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetDailyReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReviewRequest) Reset() {
	*x = GetDailyReviewRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReviewRequest) ProtoMessage() {}

func (x *GetDailyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReviewRequest.ProtoReflect.Descriptor instead.
func (*GetDailyReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{17}
}

type DailyReviewResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecommendedNext []*v1.NoteReference    `protobuf:"bytes,1,rep,name=recommended_next,json=recommendedNext,proto3" json:"recommended_next,omitempty"`
	DueQuestions    []*v1.ReviewQuestion   `protobuf:"bytes,2,rep,name=due_questions,json=dueQuestions,proto3" json:"due_questions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyReviewResponse) Reset() {
	*x = DailyReviewResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReviewResponse) ProtoMessage() {}

func (x *DailyReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReviewResponse.ProtoReflect.Descriptor instead.
func (*DailyReviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{18}
}

func (x *DailyReviewResponse) GetRecommendedNext() []*v1.NoteReference {
	if x != nil {
		return x.RecommendedNext
	}
	return nil
}

func (x *DailyReviewResponse) GetDueQuestions() []*v1.ReviewQuestion {
	if x != nil {
		return x.DueQuestions
	}
	return nil
}

type CreateAIRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NoteIds       []int64                `protobuf:"varint,2,rep,packed,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIRecommendationRequest) Reset() {
	*x = CreateAIRecommendationRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIRecommendationRequest) ProtoMessage() {}

func (x *CreateAIRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIRecommendationRequest.ProtoReflect.Descriptor instead.
func (*CreateAIRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAIRecommendationRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateAIRecommendationRequest) GetNoteIds() []int64 {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

type AIRecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	References    []*v1.NoteReference    `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIRecommendationResponse) Reset() {
	*x = AIRecommendationResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIRecommendationResponse) ProtoMessage() {}

func (x *AIRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIRecommendationResponse.ProtoReflect.Descriptor instead.
func (*AIRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{20}
}

func (x *AIRecommendationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AIRecommendationResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AIRecommendationResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AIRecommendationResponse) GetReferences() []*v1.NoteReference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *AIRecommendationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListRecommendationSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationSessionsRequest) Reset() {
	*x = ListRecommendationSessionsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationSessionsRequest) ProtoMessage() {}

func (x *ListRecommendationSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendationSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{21}
}

func (x *ListRecommendationSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRecommendationSessionsResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Sessions      []*RecommendationSessionHistoryItem `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationSessionsResponse) Reset() {
	*x = ListRecommendationSessionsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationSessionsResponse) ProtoMessage() {}

func (x *ListRecommendationSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendationSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{22}
}

func (x *ListRecommendationSessionsResponse) GetSessions() []*RecommendationSessionHistoryItem {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type RecommendationSessionHistoryItem struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                    `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Result        *AIRecommendationResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	CreatedAt     string                    `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationSessionHistoryItem) Reset() {
	*x = RecommendationSessionHistoryItem{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationSessionHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationSessionHistoryItem) ProtoMessage() {}

func (x *RecommendationSessionHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationSessionHistoryItem.ProtoReflect.Descriptor instead.
func (*RecommendationSessionHistoryItem) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{23}
}

func (x *RecommendationSessionHistoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendationSessionHistoryItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RecommendationSessionHistoryItem) GetResult() *AIRecommendationResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RecommendationSessionHistoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteRecommendationSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecommendationSessionRequest) Reset() {
	*x = DeleteRecommendationSessionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecommendationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecommendationSessionRequest) ProtoMessage() {}

func (x *DeleteRecommendationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecommendationSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecommendationSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRecommendationSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRecommendationSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecommendationSessionResponse) Reset() {
	*x = DeleteRecommendationSessionResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecommendationSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecommendationSessionResponse) ProtoMessage() {}

func (x *DeleteRecommendationSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecommendationSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecommendationSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteRecommendationSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateResearchSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NoteIds       []int64                `protobuf:"varint,2,rep,packed,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResearchSessionRequest) Reset() {
	*x = CreateResearchSessionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResearchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResearchSessionRequest) ProtoMessage() {}

func (x *CreateResearchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResearchSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateResearchSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{26}
}

func (x *CreateResearchSessionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateResearchSessionRequest) GetNoteIds() []int64 {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

type ResearchSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic          string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Summary        string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Outline        []string               `protobuf:"bytes,4,rep,name=outline,proto3" json:"outline,omitempty"`
	Gaps           []string               `protobuf:"bytes,5,rep,name=gaps,proto3" json:"gaps,omitempty"`
	Questions      []string               `protobuf:"bytes,6,rep,name=questions,proto3" json:"questions,omitempty"`
	SuggestedNotes []string               `protobuf:"bytes,7,rep,name=suggested_notes,json=suggestedNotes,proto3" json:"suggested_notes,omitempty"`
	RelatedNotes   []*v1.NoteReference    `protobuf:"bytes,8,rep,name=related_notes,json=relatedNotes,proto3" json:"related_notes,omitempty"`
	UsedAi         bool                   `protobuf:"varint,9,opt,name=used_ai,json=usedAi,proto3" json:"used_ai,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResearchSessionResponse) Reset() {
	*x = ResearchSessionResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchSessionResponse) ProtoMessage() {}

func (x *ResearchSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchSessionResponse.ProtoReflect.Descriptor instead.
func (*ResearchSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{27}
}

func (x *ResearchSessionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResearchSessionResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ResearchSessionResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResearchSessionResponse) GetOutline() []string {
	if x != nil {
		return x.Outline
	}
	return nil
}

func (x *ResearchSessionResponse) GetGaps() []string {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *ResearchSessionResponse) GetQuestions() []string {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ResearchSessionResponse) GetSuggestedNotes() []string {
	if x != nil {
		return x.SuggestedNotes
	}
	return nil
}

func (x *ResearchSessionResponse) GetRelatedNotes() []*v1.NoteReference {
	if x != nil {
		return x.RelatedNotes
	}
	return nil
}

func (x *ResearchSessionResponse) GetUsedAi() bool {
	if x != nil {
		return x.UsedAi
	}
	return false
}

func (x *ResearchSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListResearchSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResearchSessionsRequest) Reset() {
	*x = ListResearchSessionsRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResearchSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResearchSessionsRequest) ProtoMessage() {}

func (x *ListResearchSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResearchSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListResearchSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{28}
}

func (x *ListResearchSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResearchSessionsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Sessions      []*ResearchSessionHistoryItem `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResearchSessionsResponse) Reset() {
	*x = ListResearchSessionsResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResearchSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResearchSessionsResponse) ProtoMessage() {}

func (x *ListResearchSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResearchSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListResearchSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{29}
}

func (x *ListResearchSessionsResponse) GetSessions() []*ResearchSessionHistoryItem {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ResearchSessionHistoryItem struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Result        *ResearchSessionResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	CreatedAt     string                   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchSessionHistoryItem) Reset() {
	*x = ResearchSessionHistoryItem{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchSessionHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchSessionHistoryItem) ProtoMessage() {}

func (x *ResearchSessionHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchSessionHistoryItem.ProtoReflect.Descriptor instead.
func (*ResearchSessionHistoryItem) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{30}
}

func (x *ResearchSessionHistoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResearchSessionHistoryItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ResearchSessionHistoryItem) GetResult() *ResearchSessionResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResearchSessionHistoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteResearchSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResearchSessionRequest) Reset() {
	*x = DeleteResearchSessionRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResearchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResearchSessionRequest) ProtoMessage() {}

func (x *DeleteResearchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResearchSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteResearchSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteResearchSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResearchSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResearchSessionResponse) Reset() {
	*x = DeleteResearchSessionResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResearchSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResearchSessionResponse) ProtoMessage() {}

func (x *DeleteResearchSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResearchSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteResearchSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteResearchSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateWeeklyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	NoteIds       []int64                `protobuf:"varint,2,rep,packed,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"`
	FileSources   []*FileSource          `protobuf:"bytes,3,rep,name=file_sources,json=fileSources,proto3" json:"file_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWeeklyReportRequest) Reset() {
	*x = CreateWeeklyReportRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWeeklyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeeklyReportRequest) ProtoMessage() {}

func (x *CreateWeeklyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeeklyReportRequest.ProtoReflect.Descriptor instead.
func (*CreateWeeklyReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{33}
}

func (x *CreateWeeklyReportRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWeeklyReportRequest) GetNoteIds() []int64 {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

func (x *CreateWeeklyReportRequest) GetFileSources() []*FileSource {
	if x != nil {
		return x.FileSources
	}
	return nil
}

type FileSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSource) Reset() {
	*x = FileSource{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSource) ProtoMessage() {}

func (x *FileSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSource.ProtoReflect.Descriptor instead.
func (*FileSource) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{34}
}

func (x *FileSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileSource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type WeeklyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *v1.Note               `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Sources       []*v1.NoteReference    `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Files         []*FileSource          `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyReportResponse) Reset() {
	*x = WeeklyReportResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyReportResponse) ProtoMessage() {}

func (x *WeeklyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyReportResponse.ProtoReflect.Descriptor instead.
func (*WeeklyReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{35}
}

func (x *WeeklyReportResponse) GetNote() *v1.Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *WeeklyReportResponse) GetSources() []*v1.NoteReference {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *WeeklyReportResponse) GetFiles() []*FileSource {
	if x != nil {
		return x.Files
	}
	return nil
}

type OptimizeNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeNoteRequest) Reset() {
	*x = OptimizeNoteRequest{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeNoteRequest) ProtoMessage() {}

func (x *OptimizeNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeNoteRequest.ProtoReflect.Descriptor instead.
func (*OptimizeNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{36}
}

func (x *OptimizeNoteRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *OptimizeNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OptimizeNoteRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type OptimizeNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	References    []*v1.NoteReference    `protobuf:"bytes,3,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeNoteResponse) Reset() {
	*x = OptimizeNoteResponse{}
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeNoteResponse) ProtoMessage() {}

func (x *OptimizeNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intelligence_v1_intelligence_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeNoteResponse.ProtoReflect.Descriptor instead.
func (*OptimizeNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{37}
}

func (x *OptimizeNoteResponse) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *OptimizeNoteResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *OptimizeNoteResponse) GetReferences() []*v1.NoteReference {
	if x != nil {
		return x.References
	}
	return nil
}

var File_api_proto_intelligence_v1_intelligence_proto protoreflect.FileDescriptor

const file_api_proto_intelligence_v1_intelligence_proto_rawDesc = "" +
	"\n" +
	",api/proto/intelligence/v1/intelligence.proto\x12\x14note.intelligence.v1\x1a api/proto/common/v1/common.proto\"I\n" +
	"\x16GetNoteInsightsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached\"\xde\x03\n" +
	"\x14NoteInsightsResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x18\n" +
	"\aoutline\x18\x02 \x03(\tR\aoutline\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12%\n" +
	"\x0esuggested_tags\x18\x04 \x03(\tR\rsuggestedTags\x12#\n" +
	"\rquality_score\x18\x05 \x01(\x05R\fqualityScore\x12I\n" +
	"\x0equality_issues\x18\x06 \x03(\v2\".note.intelligence.v1.QualityIssueR\rqualityIssues\x12>\n" +
	"\n" +
	"flashcards\x18\a \x03(\v2\x1e.note.common.v1.ReviewQuestionR\n" +
	"flashcards\x12G\n" +
	"\x0frecommendations\x18\b \x03(\v2\x1d.note.common.v1.NoteReferenceR\x0frecommendations\x12=\n" +
	"\x05links\x18\t \x01(\v2'.note.intelligence.v1.NoteLinksResponseR\x05links\x12\x17\n" +
	"\aused_ai\x18\n" +
	" \x01(\bR\x06usedAi\"x\n" +
	"\fQualityIssue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\"-\n" +
	"\x12SuggestTagsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"B\n" +
	"\x13SuggestTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x17\n" +
	"\aused_ai\x18\x02 \x01(\bR\x06usedAi\"8\n" +
	"\x1dGetNoteRecommendationsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"R\n" +
	"\x1bNoteRecommendationsResponse\x123\n" +
	"\x05notes\x18\x01 \x03(\v2\x1d.note.common.v1.NoteReferenceR\x05notes\".\n" +
	"\x13GetNoteLinksRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"\x89\x01\n" +
	"\x11NoteLinksResponse\x129\n" +
	"\bincoming\x18\x01 \x03(\v2\x1d.note.common.v1.NoteReferenceR\bincoming\x129\n" +
	"\boutgoing\x18\x02 \x03(\v2\x1d.note.common.v1.NoteReferenceR\boutgoing\"5\n" +
	"\x1aListReviewQuestionsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"[\n" +
	"\x1bListReviewQuestionsResponse\x12<\n" +
	"\tquestions\x18\x01 \x03(\v2\x1e.note.common.v1.ReviewQuestionR\tquestions\"\x82\x01\n" +
	"\x1bCreateReviewQuestionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"O\n" +
	"\x1eGenerateReviewQuestionsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"[\n" +
	"\x1fGenerateReviewQuestionsResponse\x128\n" +
	"\acreated\x18\x01 \x03(\v2\x1e.note.common.v1.ReviewQuestionR\acreated\"\x8b\x01\n" +
	"\x1bUpdateReviewQuestionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\"W\n" +
	"\x1bDeleteReviewQuestionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\".\n" +
	"\x1cDeleteReviewQuestionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x17\n" +
	"\x15GetDailyReviewRequest\"\xa4\x01\n" +
	"\x13DailyReviewResponse\x12H\n" +
	"\x10recommended_next\x18\x01 \x03(\v2\x1d.note.common.v1.NoteReferenceR\x0frecommendedNext\x12C\n" +
	"\rdue_questions\x18\x02 \x03(\v2\x1e.note.common.v1.ReviewQuestionR\fdueQuestions\"P\n" +
	"\x1dCreateAIRecommendationRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bnote_ids\x18\x02 \x03(\x03R\anoteIds\"\xb8\x01\n" +
	"\x18AIRecommendationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12=\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x1d.note.common.v1.NoteReferenceR\n" +
	"references\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"9\n" +
	"!ListRecommendationSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"x\n" +
	"\"ListRecommendationSessionsResponse\x12R\n" +
	"\bsessions\x18\x01 \x03(\v26.note.intelligence.v1.RecommendationSessionHistoryItemR\bsessions\"\xaf\x01\n" +
	" RecommendationSessionHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..note.intelligence.v1.AIRecommendationResponseR\x06result\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"4\n" +
	"\"DeleteRecommendationSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"#DeleteRecommendationSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"O\n" +
	"\x1cCreateResearchSessionRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bnote_ids\x18\x02 \x03(\x03R\anoteIds\"\xca\x02\n" +
	"\x17ResearchSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\aoutline\x18\x04 \x03(\tR\aoutline\x12\x12\n" +
	"\x04gaps\x18\x05 \x03(\tR\x04gaps\x12\x1c\n" +
	"\tquestions\x18\x06 \x03(\tR\tquestions\x12'\n" +
	"\x0fsuggested_notes\x18\a \x03(\tR\x0esuggestedNotes\x12B\n" +
	"\rrelated_notes\x18\b \x03(\v2\x1d.note.common.v1.NoteReferenceR\frelatedNotes\x12\x17\n" +
	"\aused_ai\x18\t \x01(\bR\x06usedAi\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"3\n" +
	"\x1bListResearchSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"l\n" +
	"\x1cListResearchSessionsResponse\x12L\n" +
	"\bsessions\x18\x01 \x03(\v20.note.intelligence.v1.ResearchSessionHistoryItemR\bsessions\"\xa8\x01\n" +
	"\x1aResearchSessionHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12E\n" +
	"\x06result\x18\x03 \x01(\v2-.note.intelligence.v1.ResearchSessionResponseR\x06result\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\".\n" +
	"\x1cDeleteResearchSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x1dDeleteResearchSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x91\x01\n" +
	"\x19CreateWeeklyReportRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\bnote_ids\x18\x02 \x03(\x03R\anoteIds\x12C\n" +
	"\ffile_sources\x18\x03 \x03(\v2 .note.intelligence.v1.FileSourceR\vfileSources\":\n" +
	"\n" +
	"FileSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb1\x01\n" +
	"\x14WeeklyReportResponse\x12(\n" +
	"\x04note\x18\x01 \x01(\v2\x14.note.common.v1.NoteR\x04note\x127\n" +
	"\asources\x18\x02 \x03(\v2\x1d.note.common.v1.NoteReferenceR\asources\x126\n" +
	"\x05files\x18\x03 \x03(\v2 .note.intelligence.v1.FileSourceR\x05files\"`\n" +
	"\x13OptimizeNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x03 \x01(\tR\bmarkdown\"\x85\x01\n" +
	"\x14OptimizeNoteResponse\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\x12=\n" +
	"\n" +
	"references\x18\x03 \x03(\v2\x1d.note.common.v1.NoteReferenceR\n" +
	"references2\x8f\x11\n" +
	"\x13IntelligenceService\x12k\n" +
	"\x0fGetNoteInsights\x12,.note.intelligence.v1.GetNoteInsightsRequest\x1a*.note.intelligence.v1.NoteInsightsResponse\x12b\n" +
	"\vSuggestTags\x12(.note.intelligence.v1.SuggestTagsRequest\x1a).note.intelligence.v1.SuggestTagsResponse\x12\x80\x01\n" +
	"\x16GetNoteRecommendations\x123.note.intelligence.v1.GetNoteRecommendationsRequest\x1a1.note.intelligence.v1.NoteRecommendationsResponse\x12b\n" +
	"\fGetNoteLinks\x12).note.intelligence.v1.GetNoteLinksRequest\x1a'.note.intelligence.v1.NoteLinksResponse\x12z\n" +
	"\x13ListReviewQuestions\x120.note.intelligence.v1.ListReviewQuestionsRequest\x1a1.note.intelligence.v1.ListReviewQuestionsResponse\x12i\n" +
	"\x14CreateReviewQuestion\x121.note.intelligence.v1.CreateReviewQuestionRequest\x1a\x1e.note.common.v1.ReviewQuestion\x12\x86\x01\n" +
	"\x17GenerateReviewQuestions\x124.note.intelligence.v1.GenerateReviewQuestionsRequest\x1a5.note.intelligence.v1.GenerateReviewQuestionsResponse\x12i\n" +
	"\x14UpdateReviewQuestion\x121.note.intelligence.v1.UpdateReviewQuestionRequest\x1a\x1e.note.common.v1.ReviewQuestion\x12}\n" +
	"\x14DeleteReviewQuestion\x121.note.intelligence.v1.DeleteReviewQuestionRequest\x1a2.note.intelligence.v1.DeleteReviewQuestionResponse\x12h\n" +
	"\x0eGetDailyReview\x12+.note.intelligence.v1.GetDailyReviewRequest\x1a).note.intelligence.v1.DailyReviewResponse\x12}\n" +
	"\x16CreateAIRecommendation\x123.note.intelligence.v1.CreateAIRecommendationRequest\x1a..note.intelligence.v1.AIRecommendationResponse\x12\x8f\x01\n" +
	"\x1aListRecommendationSessions\x127.note.intelligence.v1.ListRecommendationSessionsRequest\x1a8.note.intelligence.v1.ListRecommendationSessionsResponse\x12\x92\x01\n" +
	"\x1bDeleteRecommendationSession\x128.note.intelligence.v1.DeleteRecommendationSessionRequest\x1a9.note.intelligence.v1.DeleteRecommendationSessionResponse\x12z\n" +
	"\x15CreateResearchSession\x122.note.intelligence.v1.CreateResearchSessionRequest\x1a-.note.intelligence.v1.ResearchSessionResponse\x12}\n" +
	"\x14ListResearchSessions\x121.note.intelligence.v1.ListResearchSessionsRequest\x1a2.note.intelligence.v1.ListResearchSessionsResponse\x12\x80\x01\n" +
	"\x15DeleteResearchSession\x122.note.intelligence.v1.DeleteResearchSessionRequest\x1a3.note.intelligence.v1.DeleteResearchSessionResponse\x12q\n" +
	"\x12CreateWeeklyReport\x12/.note.intelligence.v1.CreateWeeklyReportRequest\x1a*.note.intelligence.v1.WeeklyReportResponse\x12e\n" +
	"\fOptimizeNote\x12).note.intelligence.v1.OptimizeNoteRequest\x1a*.note.intelligence.v1.OptimizeNoteResponseB/Z-note/api/proto/intelligence/v1;intelligencev1b\x06proto3"

var (
	file_api_proto_intelligence_v1_intelligence_proto_rawDescOnce sync.Once
	file_api_proto_intelligence_v1_intelligence_proto_rawDescData []byte
)

func file_api_proto_intelligence_v1_intelligence_proto_rawDescGZIP() []byte {
	file_api_proto_intelligence_v1_intelligence_proto_rawDescOnce.Do(func() {
		file_api_proto_intelligence_v1_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_intelligence_v1_intelligence_proto_rawDesc), len(file_api_proto_intelligence_v1_intelligence_proto_rawDesc)))
	})
	return file_api_proto_intelligence_v1_intelligence_proto_rawDescData
}

var file_api_proto_intelligence_v1_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_api_proto_intelligence_v1_intelligence_proto_goTypes = []any{
	(*GetNoteInsightsRequest)(nil),              // 0: note.intelligence.v1.GetNoteInsightsRequest
	(*NoteInsightsResponse)(nil),                // 1: note.intelligence.v1.NoteInsightsResponse
	(*QualityIssue)(nil),                        // 2: note.intelligence.v1.QualityIssue
	(*SuggestTagsRequest)(nil),                  // 3: note.intelligence.v1.SuggestTagsRequest
	(*SuggestTagsResponse)(nil),                 // 4: note.intelligence.v1.SuggestTagsResponse
	(*GetNoteRecommendationsRequest)(nil),       // 5: note.intelligence.v1.GetNoteRecommendationsRequest
	(*NoteRecommendationsResponse)(nil),         // 6: note.intelligence.v1.NoteRecommendationsResponse
	(*GetNoteLinksRequest)(nil),                 // 7: note.intelligence.v1.GetNoteLinksRequest
	(*NoteLinksResponse)(nil),                   // 8: note.intelligence.v1.NoteLinksResponse
	(*ListReviewQuestionsRequest)(nil),          // 9: note.intelligence.v1.ListReviewQuestionsRequest
	(*ListReviewQuestionsResponse)(nil),         // 10: note.intelligence.v1.ListReviewQuestionsResponse
	(*CreateReviewQuestionRequest)(nil),         // 11: note.intelligence.v1.CreateReviewQuestionRequest
	(*GenerateReviewQuestionsRequest)(nil),      // 12: note.intelligence.v1.GenerateReviewQuestionsRequest
	(*GenerateReviewQuestionsResponse)(nil),     // 13: note.intelligence.v1.GenerateReviewQuestionsResponse
	(*UpdateReviewQuestionRequest)(nil),         // 14: note.intelligence.v1.UpdateReviewQuestionRequest
	(*DeleteReviewQuestionRequest)(nil),         // 15: note.intelligence.v1.DeleteReviewQuestionRequest
	(*DeleteReviewQuestionResponse)(nil),        // 16: note.intelligence.v1.DeleteReviewQuestionResponse
	(*GetDailyReviewRequest)(nil),               // 17: note.intelligence.v1.GetDailyReviewRequest
	(*DailyReviewResponse)(nil),                 // 18: note.intelligence.v1.DailyReviewResponse
	(*CreateAIRecommendationRequest)(nil),       // 19: note.intelligence.v1.CreateAIRecommendationRequest
	(*AIRecommendationResponse)(nil),            // 20: note.intelligence.v1.AIRecommendationResponse
	(*ListRecommendationSessionsRequest)(nil),   // 21: note.intelligence.v1.ListRecommendationSessionsRequest
	(*ListRecommendationSessionsResponse)(nil),  // 22: note.intelligence.v1.ListRecommendationSessionsResponse
	(*RecommendationSessionHistoryItem)(nil),    // 23: note.intelligence.v1.RecommendationSessionHistoryItem
	(*DeleteRecommendationSessionRequest)(nil),  // 24: note.intelligence.v1.DeleteRecommendationSessionRequest
	(*DeleteRecommendationSessionResponse)(nil), // 25: note.intelligence.v1.DeleteRecommendationSessionResponse
	(*CreateResearchSessionRequest)(nil),        // 26: note.intelligence.v1.CreateResearchSessionRequest
	(*ResearchSessionResponse)(nil),             // 27: note.intelligence.v1.ResearchSessionResponse
	(*ListResearchSessionsRequest)(nil),         // 28: note.intelligence.v1.ListResearchSessionsRequest
	(*ListResearchSessionsResponse)(nil),        // 29: note.intelligence.v1.ListResearchSessionsResponse
	(*ResearchSessionHistoryItem)(nil),          // 30: note.intelligence.v1.ResearchSessionHistoryItem
	(*DeleteResearchSessionRequest)(nil),        // 31: note.intelligence.v1.DeleteResearchSessionRequest
	(*DeleteResearchSessionResponse)(nil),       // 32: note.intelligence.v1.DeleteResearchSessionResponse
	(*CreateWeeklyReportRequest)(nil),           // 33: note.intelligence.v1.CreateWeeklyReportRequest
	(*FileSource)(nil),                          // 34: note.intelligence.v1.FileSource
	(*WeeklyReportResponse)(nil),                // 35: note.intelligence.v1.WeeklyReportResponse
	(*OptimizeNoteRequest)(nil),                 // 36: note.intelligence.v1.OptimizeNoteRequest
	(*OptimizeNoteResponse)(nil),                // 37: note.intelligence.v1.OptimizeNoteResponse
	(*v1.ReviewQuestion)(nil),                   // 38: note.common.v1.ReviewQuestion
	(*v1.NoteReference)(nil),                    // 39: note.common.v1.NoteReference
	(*v1.Note)(nil),                             // 40: note.common.v1.Note
}
var file_api_proto_intelligence_v1_intelligence_proto_depIdxs = []int32{
	2,  // 0: note.intelligence.v1.NoteInsightsResponse.quality_issues:type_name -> note.intelligence.v1.QualityIssue
	38, // 1: note.intelligence.v1.NoteInsightsResponse.flashcards:type_name -> note.common.v1.ReviewQuestion
	39, // 2: note.intelligence.v1.NoteInsightsResponse.recommendations:type_name -> note.common.v1.NoteReference
	8,  // 3: note.intelligence.v1.NoteInsightsResponse.links:type_name -> note.intelligence.v1.NoteLinksResponse
	39, // 4: note.intelligence.v1.NoteRecommendationsResponse.notes:type_name -> note.common.v1.NoteReference
	39, // 5: note.intelligence.v1.NoteLinksResponse.incoming:type_name -> note.common.v1.NoteReference
	39, // 6: note.intelligence.v1.NoteLinksResponse.outgoing:type_name -> note.common.v1.NoteReference
	38, // 7: note.intelligence.v1.ListReviewQuestionsResponse.questions:type_name -> note.common.v1.ReviewQuestion
	38, // 8: note.intelligence.v1.GenerateReviewQuestionsResponse.created:type_name -> note.common.v1.ReviewQuestion
	39, // 9: note.intelligence.v1.DailyReviewResponse.recommended_next:type_name -> note.common.v1.NoteReference
	38, // 10: note.intelligence.v1.DailyReviewResponse.due_questions:type_name -> note.common.v1.ReviewQuestion
	39, // 11: note.intelligence.v1.AIRecommendationResponse.references:type_name -> note.common.v1.NoteReference
	23, // 12: note.intelligence.v1.ListRecommendationSessionsResponse.sessions:type_name -> note.intelligence.v1.RecommendationSessionHistoryItem
	20, // 13: note.intelligence.v1.RecommendationSessionHistoryItem.result:type_name -> note.intelligence.v1.AIRecommendationResponse
	39, // 14: note.intelligence.v1.ResearchSessionResponse.related_notes:type_name -> note.common.v1.NoteReference
	30, // 15: note.intelligence.v1.ListResearchSessionsResponse.sessions:type_name -> note.intelligence.v1.ResearchSessionHistoryItem
	27, // 16: note.intelligence.v1.ResearchSessionHistoryItem.result:type_name -> note.intelligence.v1.ResearchSessionResponse
	34, // 17: note.intelligence.v1.CreateWeeklyReportRequest.file_sources:type_name -> note.intelligence.v1.FileSource
	40, // 18: note.intelligence.v1.WeeklyReportResponse.note:type_name -> note.common.v1.Note
	39, // 19: note.intelligence.v1.WeeklyReportResponse.sources:type_name -> note.common.v1.NoteReference
	34, // 20: note.intelligence.v1.WeeklyReportResponse.files:type_name -> note.intelligence.v1.FileSource
	39, // 21: note.intelligence.v1.OptimizeNoteResponse.references:type_name -> note.common.v1.NoteReference
	0,  // 22: note.intelligence.v1.IntelligenceService.GetNoteInsights:input_type -> note.intelligence.v1.GetNoteInsightsRequest
	3,  // 23: note.intelligence.v1.IntelligenceService.SuggestTags:input_type -> note.intelligence.v1.SuggestTagsRequest
	5,  // 24: note.intelligence.v1.IntelligenceService.GetNoteRecommendations:input_type -> note.intelligence.v1.GetNoteRecommendationsRequest
	7,  // 25: note.intelligence.v1.IntelligenceService.GetNoteLinks:input_type -> note.intelligence.v1.GetNoteLinksRequest
	9,  // 26: note.intelligence.v1.IntelligenceService.ListReviewQuestions:input_type -> note.intelligence.v1.ListReviewQuestionsRequest
	11, // 27: note.intelligence.v1.IntelligenceService.CreateReviewQuestion:input_type -> note.intelligence.v1.CreateReviewQuestionRequest
	12, // 28: note.intelligence.v1.IntelligenceService.GenerateReviewQuestions:input_type -> note.intelligence.v1.GenerateReviewQuestionsRequest
	14, // 29: note.intelligence.v1.IntelligenceService.UpdateReviewQuestion:input_type -> note.intelligence.v1.UpdateReviewQuestionRequest
	15, // 30: note.intelligence.v1.IntelligenceService.DeleteReviewQuestion:input_type -> note.intelligence.v1.DeleteReviewQuestionRequest
	17, // 31: note.intelligence.v1.IntelligenceService.GetDailyReview:input_type -> note.intelligence.v1.GetDailyReviewRequest
	19, // 32: note.intelligence.v1.IntelligenceService.CreateAIRecommendation:input_type -> note.intelligence.v1.CreateAIRecommendationRequest
	21, // 33: note.intelligence.v1.IntelligenceService.ListRecommendationSessions:input_type -> note.intelligence.v1.ListRecommendationSessionsRequest
	24, // 34: note.intelligence.v1.IntelligenceService.DeleteRecommendationSession:input_type -> note.intelligence.v1.DeleteRecommendationSessionRequest
	26, // 35: note.intelligence.v1.IntelligenceService.CreateResearchSession:input_type -> note.intelligence.v1.CreateResearchSessionRequest
	28, // 36: note.intelligence.v1.IntelligenceService.ListResearchSessions:input_type -> note.intelligence.v1.ListResearchSessionsRequest
	31, // 37: note.intelligence.v1.IntelligenceService.DeleteResearchSession:input_type -> note.intelligence.v1.DeleteResearchSessionRequest
	33, // 38: note.intelligence.v1.IntelligenceService.CreateWeeklyReport:input_type -> note.intelligence.v1.CreateWeeklyReportRequest
	36, // 39: note.intelligence.v1.IntelligenceService.OptimizeNote:input_type -> note.intelligence.v1.OptimizeNoteRequest
	1,  // 40: note.intelligence.v1.IntelligenceService.GetNoteInsights:output_type -> note.intelligence.v1.NoteInsightsResponse
	4,  // 41: note.intelligence.v1.IntelligenceService.SuggestTags:output_type -> note.intelligence.v1.SuggestTagsResponse
	6,  // 42: note.intelligence.v1.IntelligenceService.GetNoteRecommendations:output_type -> note.intelligence.v1.NoteRecommendationsResponse
	8,  // 43: note.intelligence.v1.IntelligenceService.GetNoteLinks:output_type -> note.intelligence.v1.NoteLinksResponse
	10, // 44: note.intelligence.v1.IntelligenceService.ListReviewQuestions:output_type -> note.intelligence.v1.ListReviewQuestionsResponse
	38, // 45: note.intelligence.v1.IntelligenceService.CreateReviewQuestion:output_type -> note.common.v1.ReviewQuestion
	13, // 46: note.intelligence.v1.IntelligenceService.GenerateReviewQuestions:output_type -> note.intelligence.v1.GenerateReviewQuestionsResponse
	38, // 47: note.intelligence.v1.IntelligenceService.UpdateReviewQuestion:output_type -> note.common.v1.ReviewQuestion
	16, // 48: note.intelligence.v1.IntelligenceService.DeleteReviewQuestion:output_type -> note.intelligence.v1.DeleteReviewQuestionResponse
	18, // 49: note.intelligence.v1.IntelligenceService.GetDailyReview:output_type -> note.intelligence.v1.DailyReviewResponse
	20, // 50: note.intelligence.v1.IntelligenceService.CreateAIRecommendation:output_type -> note.intelligence.v1.AIRecommendationResponse
	22, // 51: note.intelligence.v1.IntelligenceService.ListRecommendationSessions:output_type -> note.intelligence.v1.ListRecommendationSessionsResponse
	25, // 52: note.intelligence.v1.IntelligenceService.DeleteRecommendationSession:output_type -> note.intelligence.v1.DeleteRecommendationSessionResponse
	27, // 53: note.intelligence.v1.IntelligenceService.CreateResearchSession:output_type -> note.intelligence.v1.ResearchSessionResponse
	29, // 54: note.intelligence.v1.IntelligenceService.ListResearchSessions:output_type -> note.intelligence.v1.ListResearchSessionsResponse
	32, // 55: note.intelligence.v1.IntelligenceService.DeleteResearchSession:output_type -> note.intelligence.v1.DeleteResearchSessionResponse
	35, // 56: note.intelligence.v1.IntelligenceService.CreateWeeklyReport:output_type -> note.intelligence.v1.WeeklyReportResponse
	37, // 57: note.intelligence.v1.IntelligenceService.OptimizeNote:output_type -> note.intelligence.v1.OptimizeNoteResponse
	40, // [40:58] is the sub-list for method output_type
	22, // [22:40] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_intelligence_v1_intelligence_proto_init() }
func file_api_proto_intelligence_v1_intelligence_proto_init() {
	if File_api_proto_intelligence_v1_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_intelligence_v1_intelligence_proto_rawDesc), len(file_api_proto_intelligence_v1_intelligence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_intelligence_v1_intelligence_proto_goTypes,
		DependencyIndexes: file_api_proto_intelligence_v1_intelligence_proto_depIdxs,
		MessageInfos:      file_api_proto_intelligence_v1_intelligence_proto_msgTypes,
	}.Build()
	File_api_proto_intelligence_v1_intelligence_proto = out.File
	file_api_proto_intelligence_v1_intelligence_proto_goTypes = nil
	file_api_proto_intelligence_v1_intelligence_proto_depIdxs = nil
}
