// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Note 是所有笔记服务的核心实体。
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,4,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Html          string                 `protobuf:"bytes,5,opt,name=html,proto3" json:"html,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "unfinished" | "completed"
	IsPinned      bool                   `protobuf:"varint,8,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsArchived    bool                   `protobuf:"varint,9,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Note) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *Note) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Note) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Note) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Note) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Note) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Note) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Note) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NoteBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // paragraph | todo | heading1 | code | quote | table
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Checked       bool                   `protobuf:"varint,7,opt,name=checked,proto3" json:"checked,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteBlock) Reset() {
	*x = NoteBlock{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteBlock) ProtoMessage() {}

func (x *NoteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteBlock.ProtoReflect.Descriptor instead.
func (*NoteBlock) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *NoteBlock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoteBlock) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *NoteBlock) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *NoteBlock) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *NoteBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NoteBlock) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteBlock) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *NoteBlock) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NoteBlock) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Idx           int32                  `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,5,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chunk) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *Chunk) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type KnowledgeCard struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Front          string                 `protobuf:"bytes,2,opt,name=front,proto3" json:"front,omitempty"`
	Back           string                 `protobuf:"bytes,3,opt,name=back,proto3" json:"back,omitempty"`
	Tags           []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // active | archived | mastered
	ReviewStage    int32                  `protobuf:"varint,6,opt,name=review_stage,json=reviewStage,proto3" json:"review_stage,omitempty"`
	LastReviewedAt string                 `protobuf:"bytes,7,opt,name=last_reviewed_at,json=lastReviewedAt,proto3" json:"last_reviewed_at,omitempty"`
	NextReviewAt   string                 `protobuf:"bytes,8,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeCard) Reset() {
	*x = KnowledgeCard{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeCard) ProtoMessage() {}

func (x *KnowledgeCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeCard.ProtoReflect.Descriptor instead.
func (*KnowledgeCard) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeCard) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeCard) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *KnowledgeCard) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *KnowledgeCard) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowledgeCard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KnowledgeCard) GetReviewStage() int32 {
	if x != nil {
		return x.ReviewStage
	}
	return 0
}

func (x *KnowledgeCard) GetLastReviewedAt() string {
	if x != nil {
		return x.LastReviewedAt
	}
	return ""
}

func (x *KnowledgeCard) GetNextReviewAt() string {
	if x != nil {
		return x.NextReviewAt
	}
	return ""
}

func (x *KnowledgeCard) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KnowledgeCard) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReviewQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // manual | ai
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewQuestion) Reset() {
	*x = ReviewQuestion{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewQuestion) ProtoMessage() {}

func (x *ReviewQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewQuestion.ProtoReflect.Descriptor instead.
func (*ReviewQuestion) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewQuestion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewQuestion) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *ReviewQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ReviewQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ReviewQuestion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type NoteReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteReference) Reset() {
	*x = NoteReference{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteReference) ProtoMessage() {}

func (x *NoteReference) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteReference.ProtoReflect.Descriptor instead.
func (*NoteReference) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *NoteReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoteReference) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteReference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NoteReference) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_proto_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_api_proto_common_v1_common_proto protoreflect.FileDescriptor

const file_api_proto_common_v1_common_proto_rawDesc = "" +
	"\n" +
	" api/proto/common/v1/common.proto\x12\x0enote.common.v1\"\xa1\x02\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x04 \x01(\tR\bmarkdown\x12\x12\n" +
	"\x04html\x18\x05 \x01(\tR\x04html\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1b\n" +
	"\tis_pinned\x18\b \x01(\bR\bisPinned\x12\x1f\n" +
	"\vis_archived\x18\t \x01(\bR\n" +
	"isArchived\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xec\x01\n" +
	"\tNoteBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x18\n" +
	"\achecked\x18\a \x01(\bR\achecked\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"z\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\x05R\x03idx\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x05 \x03(\x02R\tembedding\"\xa6\x02\n" +
	"\rKnowledgeCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05front\x18\x02 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x03 \x01(\tR\x04back\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\freview_stage\x18\x06 \x01(\x05R\vreviewStage\x12(\n" +
	"\x10last_reviewed_at\x18\a \x01(\tR\x0elastReviewedAt\x12$\n" +
	"\x0enext_review_at\x18\b \x01(\tR\fnextReviewAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x85\x01\n" +
	"\x0eReviewQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"]\n" +
	"\rNoteReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"5\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04codeB#Z!note/api/proto/common/v1;commonv1b\x06proto3"

var (
	file_api_proto_common_v1_common_proto_rawDescOnce sync.Once
	file_api_proto_common_v1_common_proto_rawDescData []byte
)

func file_api_proto_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_v1_common_proto_rawDesc), len(file_api_proto_common_v1_common_proto_rawDesc)))
	})
	return file_api_proto_common_v1_common_proto_rawDescData
}

var file_api_proto_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_common_v1_common_proto_goTypes = []any{
	(*Note)(nil),           // 0: note.common.v1.Note
	(*NoteBlock)(nil),      // 1: note.common.v1.NoteBlock
	(*Chunk)(nil),          // 2: note.common.v1.Chunk
	(*KnowledgeCard)(nil),  // 3: note.common.v1.KnowledgeCard
	(*ReviewQuestion)(nil), // 4: note.common.v1.ReviewQuestion
	(*NoteReference)(nil),  // 5: note.common.v1.NoteReference
	(*Pagination)(nil),     // 6: note.common.v1.Pagination
	(*Error)(nil),          // 7: note.common.v1.Error
}
var file_api_proto_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_common_v1_common_proto_init() }
func file_api_proto_common_v1_common_proto_init() {
	if File_api_proto_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_v1_common_proto_rawDesc), len(file_api_proto_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_v1_common_proto_depIdxs,
		MessageInfos:      file_api_proto_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_v1_common_proto = out.File
	file_api_proto_common_v1_common_proto_goTypes = nil
	file_api_proto_common_v1_common_proto_depIdxs = nil
}
