// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/knowledge/v1/knowledge.proto

package knowledgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "note/api/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCardsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,3,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *ListCardsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListCardsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCardsRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*v1.KnowledgeCard    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *ListCardsResponse) GetCards() []*v1.KnowledgeCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ListDueCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueCardsRequest) Reset() {
	*x = ListDueCardsRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueCardsRequest) ProtoMessage() {}

func (x *ListDueCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueCardsRequest.ProtoReflect.Descriptor instead.
func (*ListDueCardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

type ListDueCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*v1.KnowledgeCard    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueCardsResponse) Reset() {
	*x = ListDueCardsResponse{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueCardsResponse) ProtoMessage() {}

func (x *ListDueCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueCardsResponse.ProtoReflect.Descriptor instead.
func (*ListDueCardsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *ListDueCardsResponse) GetCards() []*v1.KnowledgeCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Front         string                 `protobuf:"bytes,1,opt,name=front,proto3" json:"front,omitempty"`
	Back          string                 `protobuf:"bytes,2,opt,name=back,proto3" json:"back,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCardRequest) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *CreateCardRequest) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *CreateCardRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateCardRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Front         string                 `protobuf:"bytes,2,opt,name=front,proto3" json:"front,omitempty"`
	Back          string                 `protobuf:"bytes,3,opt,name=back,proto3" json:"back,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCardRequest) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *UpdateCardRequest) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *UpdateCardRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateCardRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCardResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReviewCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Remembered    bool                   `protobuf:"varint,2,opt,name=remembered,proto3" json:"remembered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCardRequest) Reset() {
	*x = ReviewCardRequest{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCardRequest) ProtoMessage() {}

func (x *ReviewCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCardRequest.ProtoReflect.Descriptor instead.
func (*ReviewCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *ReviewCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewCardRequest) GetRemembered() bool {
	if x != nil {
		return x.Remembered
	}
	return false
}

type ReviewCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *v1.KnowledgeCard      `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Stage         int32                  `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Mastered      bool                   `protobuf:"varint,3,opt,name=mastered,proto3" json:"mastered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCardResponse) Reset() {
	*x = ReviewCardResponse{}
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCardResponse) ProtoMessage() {}

func (x *ReviewCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_knowledge_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCardResponse.ProtoReflect.Descriptor instead.
func (*ReviewCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *ReviewCardResponse) GetCard() *v1.KnowledgeCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *ReviewCardResponse) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *ReviewCardResponse) GetMastered() bool {
	if x != nil {
		return x.Mastered
	}
	return false
}

var File_api_proto_knowledge_v1_knowledge_proto protoreflect.FileDescriptor

const file_api_proto_knowledge_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"&api/proto/knowledge/v1/knowledge.proto\x12\x11note.knowledge.v1\x1a api/proto/common/v1/common.proto\"k\n" +
	"\x10ListCardsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10include_archived\x18\x03 \x01(\bR\x0fincludeArchived\"H\n" +
	"\x11ListCardsResponse\x123\n" +
	"\x05cards\x18\x01 \x03(\v2\x1d.note.common.v1.KnowledgeCardR\x05cards\"\x15\n" +
	"\x13ListDueCardsRequest\"K\n" +
	"\x14ListDueCardsResponse\x123\n" +
	"\x05cards\x18\x01 \x03(\v2\x1d.note.common.v1.KnowledgeCardR\x05cards\" \n" +
	"\x0eGetCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"i\n" +
	"\x11CreateCardRequest\x12\x14\n" +
	"\x05front\x18\x01 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x02 \x01(\tR\x04back\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"y\n" +
	"\x11UpdateCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05front\x18\x02 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x03 \x01(\tR\x04back\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"#\n" +
	"\x11DeleteCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteCardResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"C\n" +
	"\x11ReviewCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"remembered\x18\x02 \x01(\bR\n" +
	"remembered\"y\n" +
	"\x12ReviewCardResponse\x121\n" +
	"\x04card\x18\x01 \x01(\v2\x1d.note.common.v1.KnowledgeCardR\x04card\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\x05R\x05stage\x12\x1a\n" +
	"\bmastered\x18\x03 \x01(\bR\bmastered2\xf4\x04\n" +
	"\x10KnowledgeService\x12V\n" +
	"\tListCards\x12#.note.knowledge.v1.ListCardsRequest\x1a$.note.knowledge.v1.ListCardsResponse\x12_\n" +
	"\fListDueCards\x12&.note.knowledge.v1.ListDueCardsRequest\x1a'.note.knowledge.v1.ListDueCardsResponse\x12K\n" +
	"\aGetCard\x12!.note.knowledge.v1.GetCardRequest\x1a\x1d.note.common.v1.KnowledgeCard\x12Q\n" +
	"\n" +
	"CreateCard\x12$.note.knowledge.v1.CreateCardRequest\x1a\x1d.note.common.v1.KnowledgeCard\x12Q\n" +
	"\n" +
	"UpdateCard\x12$.note.knowledge.v1.UpdateCardRequest\x1a\x1d.note.common.v1.KnowledgeCard\x12Y\n" +
	"\n" +
	"DeleteCard\x12$.note.knowledge.v1.DeleteCardRequest\x1a%.note.knowledge.v1.DeleteCardResponse\x12Y\n" +
	"\n" +
	"ReviewCard\x12$.note.knowledge.v1.ReviewCardRequest\x1a%.note.knowledge.v1.ReviewCardResponseB)Z'note/api/proto/knowledge/v1;knowledgev1b\x06proto3"

var (
	file_api_proto_knowledge_v1_knowledge_proto_rawDescOnce sync.Once
	file_api_proto_knowledge_v1_knowledge_proto_rawDescData []byte
)

func file_api_proto_knowledge_v1_knowledge_proto_rawDescGZIP() []byte {
	file_api_proto_knowledge_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_api_proto_knowledge_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_knowledge_v1_knowledge_proto_rawDesc), len(file_api_proto_knowledge_v1_knowledge_proto_rawDesc)))
	})
	return file_api_proto_knowledge_v1_knowledge_proto_rawDescData
}

var file_api_proto_knowledge_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_knowledge_v1_knowledge_proto_goTypes = []any{
	(*ListCardsRequest)(nil),     // 0: note.knowledge.v1.ListCardsRequest
	(*ListCardsResponse)(nil),    // 1: note.knowledge.v1.ListCardsResponse
	(*ListDueCardsRequest)(nil),  // 2: note.knowledge.v1.ListDueCardsRequest
	(*ListDueCardsResponse)(nil), // 3: note.knowledge.v1.ListDueCardsResponse
	(*GetCardRequest)(nil),       // 4: note.knowledge.v1.GetCardRequest
	(*CreateCardRequest)(nil),    // 5: note.knowledge.v1.CreateCardRequest
	(*UpdateCardRequest)(nil),    // 6: note.knowledge.v1.UpdateCardRequest
	(*DeleteCardRequest)(nil),    // 7: note.knowledge.v1.DeleteCardRequest
	(*DeleteCardResponse)(nil),   // 8: note.knowledge.v1.DeleteCardResponse
	(*ReviewCardRequest)(nil),    // 9: note.knowledge.v1.ReviewCardRequest
	(*ReviewCardResponse)(nil),   // 10: note.knowledge.v1.ReviewCardResponse
	(*v1.KnowledgeCard)(nil),     // 11: note.common.v1.KnowledgeCard
}
var file_api_proto_knowledge_v1_knowledge_proto_depIdxs = []int32{
	11, // 0: note.knowledge.v1.ListCardsResponse.cards:type_name -> note.common.v1.KnowledgeCard
	11, // 1: note.knowledge.v1.ListDueCardsResponse.cards:type_name -> note.common.v1.KnowledgeCard
	11, // 2: note.knowledge.v1.ReviewCardResponse.card:type_name -> note.common.v1.KnowledgeCard
	0,  // 3: note.knowledge.v1.KnowledgeService.ListCards:input_type -> note.knowledge.v1.ListCardsRequest
	2,  // 4: note.knowledge.v1.KnowledgeService.ListDueCards:input_type -> note.knowledge.v1.ListDueCardsRequest
	4,  // 5: note.knowledge.v1.KnowledgeService.GetCard:input_type -> note.knowledge.v1.GetCardRequest
	5,  // 6: note.knowledge.v1.KnowledgeService.CreateCard:input_type -> note.knowledge.v1.CreateCardRequest
	6,  // 7: note.knowledge.v1.KnowledgeService.UpdateCard:input_type -> note.knowledge.v1.UpdateCardRequest
	7,  // 8: note.knowledge.v1.KnowledgeService.DeleteCard:input_type -> note.knowledge.v1.DeleteCardRequest
	9,  // 9: note.knowledge.v1.KnowledgeService.ReviewCard:input_type -> note.knowledge.v1.ReviewCardRequest
	1,  // 10: note.knowledge.v1.KnowledgeService.ListCards:output_type -> note.knowledge.v1.ListCardsResponse
	3,  // 11: note.knowledge.v1.KnowledgeService.ListDueCards:output_type -> note.knowledge.v1.ListDueCardsResponse
	11, // 12: note.knowledge.v1.KnowledgeService.GetCard:output_type -> note.common.v1.KnowledgeCard
	11, // 13: note.knowledge.v1.KnowledgeService.CreateCard:output_type -> note.common.v1.KnowledgeCard
	11, // 14: note.knowledge.v1.KnowledgeService.UpdateCard:output_type -> note.common.v1.KnowledgeCard
	8,  // 15: note.knowledge.v1.KnowledgeService.DeleteCard:output_type -> note.knowledge.v1.DeleteCardResponse
	10, // 16: note.knowledge.v1.KnowledgeService.ReviewCard:output_type -> note.knowledge.v1.ReviewCardResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_knowledge_v1_knowledge_proto_init() }
func file_api_proto_knowledge_v1_knowledge_proto_init() {
	if File_api_proto_knowledge_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_knowledge_v1_knowledge_proto_rawDesc), len(file_api_proto_knowledge_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_knowledge_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_api_proto_knowledge_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_api_proto_knowledge_v1_knowledge_proto_msgTypes,
	}.Build()
	File_api_proto_knowledge_v1_knowledge_proto = out.File
	file_api_proto_knowledge_v1_knowledge_proto_goTypes = nil
	file_api_proto_knowledge_v1_knowledge_proto_depIdxs = nil
}
