// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "note/api/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	AnchorNoteId  int64                  `protobuf:"varint,3,opt,name=anchor_note_id,json=anchorNoteId,proto3" json:"anchor_note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetAnchorNoteId() int64 {
	if x != nil {
		return x.AnchorNoteId
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Results       []*ChunkWithScore      `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetResults() []*ChunkWithScore {
	if x != nil {
		return x.Results
	}
	return nil
}

type ChunkWithScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	NoteTitle     string                 `protobuf:"bytes,2,opt,name=note_title,json=noteTitle,proto3" json:"note_title,omitempty"`
	ChunkId       int64                  `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkWithScore) Reset() {
	*x = ChunkWithScore{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkWithScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkWithScore) ProtoMessage() {}

func (x *ChunkWithScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkWithScore.ProtoReflect.Descriptor instead.
func (*ChunkWithScore) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkWithScore) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *ChunkWithScore) GetNoteTitle() string {
	if x != nil {
		return x.NoteTitle
	}
	return ""
}

func (x *ChunkWithScore) GetChunkId() int64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkWithScore) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkWithScore) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkWithScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	AnchorNoteId  int64                  `protobuf:"varint,3,opt,name=anchor_note_id,json=anchorNoteId,proto3" json:"anchor_note_id,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // empty | "library" | "assistant"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *AskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AskRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *AskRequest) GetAnchorNoteId() int64 {
	if x != nil {
		return x.AnchorNoteId
	}
	return 0
}

func (x *AskRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Contexts      []*ChunkWithScore      `protobuf:"bytes,3,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *AskResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetContexts() []*ChunkWithScore {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type IndexNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexNoteRequest) Reset() {
	*x = IndexNoteRequest{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexNoteRequest) ProtoMessage() {}

func (x *IndexNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexNoteRequest.ProtoReflect.Descriptor instead.
func (*IndexNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *IndexNoteRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *IndexNoteRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type IndexNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexNoteResponse) Reset() {
	*x = IndexNoteResponse{}
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexNoteResponse) ProtoMessage() {}

func (x *IndexNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexNoteResponse.ProtoReflect.Descriptor instead.
func (*IndexNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *IndexNoteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_proto_rag_v1_rag_proto protoreflect.FileDescriptor

const file_api_proto_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/rag/v1/rag.proto\x12\vnote.rag.v1\x1a api/proto/common/v1/common.proto\"`\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12$\n" +
	"\x0eanchor_note_id\x18\x03 \x01(\x03R\fanchorNoteId\"]\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x125\n" +
	"\aresults\x18\x02 \x03(\v2\x1b.note.rag.v1.ChunkWithScoreR\aresults\"\xa9\x01\n" +
	"\x0eChunkWithScore\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1d\n" +
	"\n" +
	"note_title\x18\x02 \x01(\tR\tnoteTitle\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\x03R\achunkId\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"q\n" +
	"\n" +
	"AskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12$\n" +
	"\x0eanchor_note_id\x18\x03 \x01(\x03R\fanchorNoteId\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"t\n" +
	"\vAskResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x127\n" +
	"\bcontexts\x18\x03 \x03(\v2\x1b.note.rag.v1.ChunkWithScoreR\bcontexts\"G\n" +
	"\x10IndexNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\"#\n" +
	"\x11IndexNoteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd5\x01\n" +
	"\n" +
	"RAGService\x12A\n" +
	"\x06Search\x12\x1a.note.rag.v1.SearchRequest\x1a\x1b.note.rag.v1.SearchResponse\x128\n" +
	"\x03Ask\x12\x17.note.rag.v1.AskRequest\x1a\x18.note.rag.v1.AskResponse\x12J\n" +
	"\tIndexNote\x12\x1d.note.rag.v1.IndexNoteRequest\x1a\x1e.note.rag.v1.IndexNoteResponseB\x1dZ\x1bnote/api/proto/rag/v1;ragv1b\x06proto3"

var (
	file_api_proto_rag_v1_rag_proto_rawDescOnce sync.Once
	file_api_proto_rag_v1_rag_proto_rawDescData []byte
)

func file_api_proto_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_api_proto_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_api_proto_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rag_v1_rag_proto_rawDesc), len(file_api_proto_rag_v1_rag_proto_rawDesc)))
	})
	return file_api_proto_rag_v1_rag_proto_rawDescData
}

var file_api_proto_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_rag_v1_rag_proto_goTypes = []any{
	(*SearchRequest)(nil),     // 0: note.rag.v1.SearchRequest
	(*SearchResponse)(nil),    // 1: note.rag.v1.SearchResponse
	(*ChunkWithScore)(nil),    // 2: note.rag.v1.ChunkWithScore
	(*AskRequest)(nil),        // 3: note.rag.v1.AskRequest
	(*AskResponse)(nil),       // 4: note.rag.v1.AskResponse
	(*IndexNoteRequest)(nil),  // 5: note.rag.v1.IndexNoteRequest
	(*IndexNoteResponse)(nil), // 6: note.rag.v1.IndexNoteResponse
}
var file_api_proto_rag_v1_rag_proto_depIdxs = []int32{
	2, // 0: note.rag.v1.SearchResponse.results:type_name -> note.rag.v1.ChunkWithScore
	2, // 1: note.rag.v1.AskResponse.contexts:type_name -> note.rag.v1.ChunkWithScore
	0, // 2: note.rag.v1.RAGService.Search:input_type -> note.rag.v1.SearchRequest
	3, // 3: note.rag.v1.RAGService.Ask:input_type -> note.rag.v1.AskRequest
	5, // 4: note.rag.v1.RAGService.IndexNote:input_type -> note.rag.v1.IndexNoteRequest
	1, // 5: note.rag.v1.RAGService.Search:output_type -> note.rag.v1.SearchResponse
	4, // 6: note.rag.v1.RAGService.Ask:output_type -> note.rag.v1.AskResponse
	6, // 7: note.rag.v1.RAGService.IndexNote:output_type -> note.rag.v1.IndexNoteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_rag_v1_rag_proto_init() }
func file_api_proto_rag_v1_rag_proto_init() {
	if File_api_proto_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rag_v1_rag_proto_rawDesc), len(file_api_proto_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_api_proto_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_api_proto_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_api_proto_rag_v1_rag_proto = out.File
	file_api_proto_rag_v1_rag_proto_goTypes = nil
	file_api_proto_rag_v1_rag_proto_depIdxs = nil
}
