// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/proto/workspace/v1/workspace.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "note/api/proto/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

type DashboardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Stats           map[string]int32       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NoteStatusPie   []*ChartPoint          `protobuf:"bytes,2,rep,name=note_status_pie,json=noteStatusPie,proto3" json:"note_status_pie,omitempty"`
	OverviewBars    []*ChartPoint          `protobuf:"bytes,3,rep,name=overview_bars,json=overviewBars,proto3" json:"overview_bars,omitempty"`
	NoteTrend       []*ChartPoint          `protobuf:"bytes,4,rep,name=note_trend,json=noteTrend,proto3" json:"note_trend,omitempty"`
	UnfinishedNotes []*v1.NoteReference    `protobuf:"bytes,5,rep,name=unfinished_notes,json=unfinishedNotes,proto3" json:"unfinished_notes,omitempty"`
	RecentActivity  []*v1.NoteReference    `protobuf:"bytes,6,rep,name=recent_activity,json=recentActivity,proto3" json:"recent_activity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardResponse) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *DashboardResponse) GetNoteStatusPie() []*ChartPoint {
	if x != nil {
		return x.NoteStatusPie
	}
	return nil
}

func (x *DashboardResponse) GetOverviewBars() []*ChartPoint {
	if x != nil {
		return x.OverviewBars
	}
	return nil
}

func (x *DashboardResponse) GetNoteTrend() []*ChartPoint {
	if x != nil {
		return x.NoteTrend
	}
	return nil
}

func (x *DashboardResponse) GetUnfinishedNotes() []*v1.NoteReference {
	if x != nil {
		return x.UnfinishedNotes
	}
	return nil
}

func (x *DashboardResponse) GetRecentActivity() []*v1.NoteReference {
	if x != nil {
		return x.RecentActivity
	}
	return nil
}

type ChartPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartPoint) Reset() {
	*x = ChartPoint{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartPoint) ProtoMessage() {}

func (x *ChartPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartPoint.ProtoReflect.Descriptor instead.
func (*ChartPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *ChartPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ChartPoint) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{3}
}

type GraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GraphResponse) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	QualityScore  int32                  `protobuf:"varint,5,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *GraphNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GraphNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GraphNode) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GraphNode) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *GraphNode) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int64                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        int64                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *GraphEdge) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *GraphEdge) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *GraphEdge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GraphEdge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GraphEdge) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluateQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateQualityRequest) Reset() {
	*x = EvaluateQualityRequest{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateQualityRequest) ProtoMessage() {}

func (x *EvaluateQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateQualityRequest.ProtoReflect.Descriptor instead.
func (*EvaluateQualityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluateQualityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QualityEvaluationResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*QualityEvaluationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UsedAi        bool                     `protobuf:"varint,2,opt,name=used_ai,json=usedAi,proto3" json:"used_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityEvaluationResponse) Reset() {
	*x = QualityEvaluationResponse{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityEvaluationResponse) ProtoMessage() {}

func (x *QualityEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityEvaluationResponse.ProtoReflect.Descriptor instead.
func (*QualityEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *QualityEvaluationResponse) GetItems() []*QualityEvaluationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QualityEvaluationResponse) GetUsedAi() bool {
	if x != nil {
		return x.UsedAi
	}
	return false
}

type QualityEvaluationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *v1.NoteReference      `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Issues        []string               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityEvaluationItem) Reset() {
	*x = QualityEvaluationItem{}
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityEvaluationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityEvaluationItem) ProtoMessage() {}

func (x *QualityEvaluationItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityEvaluationItem.ProtoReflect.Descriptor instead.
func (*QualityEvaluationItem) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *QualityEvaluationItem) GetNote() *v1.NoteReference {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *QualityEvaluationItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QualityEvaluationItem) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *QualityEvaluationItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *QualityEvaluationItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QualityEvaluationItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_api_proto_workspace_v1_workspace_proto protoreflect.FileDescriptor

const file_api_proto_workspace_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"&api/proto/workspace/v1/workspace.proto\x12\x11note.workspace.v1\x1a api/proto/common/v1/common.proto\"\x15\n" +
	"\x13GetDashboardRequest\"\xef\x03\n" +
	"\x11DashboardResponse\x12E\n" +
	"\x05stats\x18\x01 \x03(\v2/.note.workspace.v1.DashboardResponse.StatsEntryR\x05stats\x12E\n" +
	"\x0fnote_status_pie\x18\x02 \x03(\v2\x1d.note.workspace.v1.ChartPointR\rnoteStatusPie\x12B\n" +
	"\roverview_bars\x18\x03 \x03(\v2\x1d.note.workspace.v1.ChartPointR\foverviewBars\x12<\n" +
	"\n" +
	"note_trend\x18\x04 \x03(\v2\x1d.note.workspace.v1.ChartPointR\tnoteTrend\x12H\n" +
	"\x10unfinished_notes\x18\x05 \x03(\v2\x1d.note.common.v1.NoteReferenceR\x0funfinishedNotes\x12F\n" +
	"\x0frecent_activity\x18\x06 \x03(\v2\x1d.note.common.v1.NoteReferenceR\x0erecentActivity\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"8\n" +
	"\n" +
	"ChartPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\x11\n" +
	"\x0fGetGraphRequest\"w\n" +
	"\rGraphResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.note.workspace.v1.GraphNodeR\x05nodes\x122\n" +
	"\x05edges\x18\x02 \x03(\v2\x1c.note.workspace.v1.GraphEdgeR\x05edges\"\x9d\x01\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12#\n" +
	"\rquality_score\x18\x05 \x01(\x05R\fqualityScore\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x7f\n" +
	"\tGraphEdge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x03R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x03R\x06target\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\".\n" +
	"\x16EvaluateQualityRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"t\n" +
	"\x19QualityEvaluationResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.note.workspace.v1.QualityEvaluationItemR\x05items\x12\x17\n" +
	"\aused_ai\x18\x02 \x01(\bR\x06usedAi\"\xc2\x01\n" +
	"\x15QualityEvaluationItem\x121\n" +
	"\x04note\x18\x01 \x01(\v2\x1d.note.common.v1.NoteReferenceR\x04note\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x16\n" +
	"\x06issues\x18\x03 \x03(\tR\x06issues\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source2\xae\x02\n" +
	"\x10WorkspaceService\x12\\\n" +
	"\fGetDashboard\x12&.note.workspace.v1.GetDashboardRequest\x1a$.note.workspace.v1.DashboardResponse\x12P\n" +
	"\bGetGraph\x12\".note.workspace.v1.GetGraphRequest\x1a .note.workspace.v1.GraphResponse\x12j\n" +
	"\x0fEvaluateQuality\x12).note.workspace.v1.EvaluateQualityRequest\x1a,.note.workspace.v1.QualityEvaluationResponseB)Z'note/api/proto/workspace/v1;workspacev1b\x06proto3"

var (
	file_api_proto_workspace_v1_workspace_proto_rawDescOnce sync.Once
	file_api_proto_workspace_v1_workspace_proto_rawDescData []byte
)

func file_api_proto_workspace_v1_workspace_proto_rawDescGZIP() []byte {
	file_api_proto_workspace_v1_workspace_proto_rawDescOnce.Do(func() {
		file_api_proto_workspace_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_workspace_v1_workspace_proto_rawDesc), len(file_api_proto_workspace_v1_workspace_proto_rawDesc)))
	})
	return file_api_proto_workspace_v1_workspace_proto_rawDescData
}

var file_api_proto_workspace_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_workspace_v1_workspace_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),       // 0: note.workspace.v1.GetDashboardRequest
	(*DashboardResponse)(nil),         // 1: note.workspace.v1.DashboardResponse
	(*ChartPoint)(nil),                // 2: note.workspace.v1.ChartPoint
	(*GetGraphRequest)(nil),           // 3: note.workspace.v1.GetGraphRequest
	(*GraphResponse)(nil),             // 4: note.workspace.v1.GraphResponse
	(*GraphNode)(nil),                 // 5: note.workspace.v1.GraphNode
	(*GraphEdge)(nil),                 // 6: note.workspace.v1.GraphEdge
	(*EvaluateQualityRequest)(nil),    // 7: note.workspace.v1.EvaluateQualityRequest
	(*QualityEvaluationResponse)(nil), // 8: note.workspace.v1.QualityEvaluationResponse
	(*QualityEvaluationItem)(nil),     // 9: note.workspace.v1.QualityEvaluationItem
	nil,                               // 10: note.workspace.v1.DashboardResponse.StatsEntry
	(*v1.NoteReference)(nil),          // 11: note.common.v1.NoteReference
}
var file_api_proto_workspace_v1_workspace_proto_depIdxs = []int32{
	10, // 0: note.workspace.v1.DashboardResponse.stats:type_name -> note.workspace.v1.DashboardResponse.StatsEntry
	2,  // 1: note.workspace.v1.DashboardResponse.note_status_pie:type_name -> note.workspace.v1.ChartPoint
	2,  // 2: note.workspace.v1.DashboardResponse.overview_bars:type_name -> note.workspace.v1.ChartPoint
	2,  // 3: note.workspace.v1.DashboardResponse.note_trend:type_name -> note.workspace.v1.ChartPoint
	11, // 4: note.workspace.v1.DashboardResponse.unfinished_notes:type_name -> note.common.v1.NoteReference
	11, // 5: note.workspace.v1.DashboardResponse.recent_activity:type_name -> note.common.v1.NoteReference
	5,  // 6: note.workspace.v1.GraphResponse.nodes:type_name -> note.workspace.v1.GraphNode
	6,  // 7: note.workspace.v1.GraphResponse.edges:type_name -> note.workspace.v1.GraphEdge
	9,  // 8: note.workspace.v1.QualityEvaluationResponse.items:type_name -> note.workspace.v1.QualityEvaluationItem
	11, // 9: note.workspace.v1.QualityEvaluationItem.note:type_name -> note.common.v1.NoteReference
	0,  // 10: note.workspace.v1.WorkspaceService.GetDashboard:input_type -> note.workspace.v1.GetDashboardRequest
	3,  // 11: note.workspace.v1.WorkspaceService.GetGraph:input_type -> note.workspace.v1.GetGraphRequest
	7,  // 12: note.workspace.v1.WorkspaceService.EvaluateQuality:input_type -> note.workspace.v1.EvaluateQualityRequest
	1,  // 13: note.workspace.v1.WorkspaceService.GetDashboard:output_type -> note.workspace.v1.DashboardResponse
	4,  // 14: note.workspace.v1.WorkspaceService.GetGraph:output_type -> note.workspace.v1.GraphResponse
	8,  // 15: note.workspace.v1.WorkspaceService.EvaluateQuality:output_type -> note.workspace.v1.QualityEvaluationResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_workspace_v1_workspace_proto_init() }
func file_api_proto_workspace_v1_workspace_proto_init() {
	if File_api_proto_workspace_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_workspace_v1_workspace_proto_rawDesc), len(file_api_proto_workspace_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_workspace_v1_workspace_proto_goTypes,
		DependencyIndexes: file_api_proto_workspace_v1_workspace_proto_depIdxs,
		MessageInfos:      file_api_proto_workspace_v1_workspace_proto_msgTypes,
	}.Build()
	File_api_proto_workspace_v1_workspace_proto = out.File
	file_api_proto_workspace_v1_workspace_proto_goTypes = nil
	file_api_proto_workspace_v1_workspace_proto_depIdxs = nil
}
